### ISSUE TITLE
关于小程序中游戏类的

### ISSUE THREAD

**Issue by marty0929** [qwerty472123/wxappUnpacker#10]
小游戏的包现在是不是还不支持反编译吗？

只能解压，但是解压之后是很多js文件和两个html。如下图↓

![image](https://user-images.githubusercontent.com/5567244/37749199-db3aec4c-2dc1-11e8-8cbf-4fe2270cea4c.png)

**Comment by qwerty472123** [comment]
目前
小游戏中我的研究对象就跳一跳一个
其他小游戏都没有考虑过

**Comment by marty0929** [comment]
那现在对于game.js和res文件夹里面的资源文件现在有办法去反编译吗？ 期待你的更新

**Comment by lnyh** [comment]
目前有个小程序可以解包，但是无法还原代码。   报这种错误，变量定义不存在如list  window等

**Comment by qwerty472123** [comment]
@marty0929 
res不就是音视频混在一起了吗，个人感觉没什么影响 game.js 我就单纯把里面内容拆回各个文件，感觉剩下的除了被压缩不可还原的变量名以外差不多了。
很好奇什么包会解出WA**.js这些运行时环境中的玩意，可以给的看看吗

另外 @lnyh 如果解什么程序遇到bug 请点 open issue 按提示提供信息谢谢

**Comment by marty0929** [comment]
好的，这个是我用老版本微信通过安卓手机中系统缓存路径拿到的wxapkg文件。
[3.zip](https://github.com/qwerty472123/wxappUnpacker/files/1836791/3.zip)

**Comment by qwerty472123** [comment]
看来一下这个包 不是`跳一跳`的 可能是老版本微信不支持小游戏，所下载的小游戏支持包（而非`跳一跳`的小游戏包）
