### ISSUE TITLE
 This Package is unrecognizable, please decrypted every type of file by hand错误

### ISSUE THREAD

**Issue by yorick520** [qwerty472123/wxappUnpacker#102]
E:\wechat-by\wxappUnpacker-master\wuWxapkg.js:102
        }else throw Error("This Package is unrecognizable, please decrypted ever
y type of file by hand.")
              ^

Error: This Package is unrecognizable, please decrypted every type of file by ha
nd.
    at Array.packDone (E:\wechat-by\wxappUnpacker-master\wuWxapkg.js:102:14)
    at CntEvent.decount (E:\wechat-by\wxappUnpacker-master\wuLib.js:17:43)
    at ioLimit.runWithCb.err (E:\wechat-by\wxappUnpacker-master\wuLib.js:73:11)
    at agent (E:\wechat-by\wxappUnpacker-master\wuLib.js:54:14)
    at FSReqWrap.oncomplete (fs.js:135:15)

[小程序](https://pan.baidu.com/s/1Amgh5Az6GCXdzdkk6yh4Gg)

**Comment by codeshif** [comment]
你解错包了，你解的是腾讯的共享库，拿错了wxapkg啊，换目录中其它的wxapkg。

**Comment by codeshif** [comment]
_1123949441_133.wxapkg
文件md5：630ba17dde4fc97c19a7e288598fcd73
就是腾讯的共享拓展库， @yorick520 
你运行小程序后目录肯定不是这一个wxapkg文件，拿另外一个

**Comment by 15990240599** [comment]
Guess wxss(first turn)...
Import count info: {}
Cannot find pure import for _C[0] which is only imported 0 times. Let importing become copying.
Cannot find pure import for _C[1] which is only imported 0 times. Let importing become copying.
Cannot find pure import for _C[2] which is only imported 0 times. Let importing become copying.
Guess wxss(first turn) done.
Generate wxss(second turn)...
Generate wxss(second turn) done.
Save wxss...

大佬们  我这里出现了这样的问题  然后反编译后有文件丢失了
