### ISSUE TITLE
调整对小程序组件的支持

### ISSUE THREAD

**Issue by qwerty472123** [qwerty472123/wxappUnpacker#117]
与我之前认为的不同，有组件的小程序将会在`app-service.js`下存放关于组建的配置文件等信息。
另外这里有一套似乎解析出来与`page-frame.html`不完全一样内容的wxml渲染代码。

欢迎补充关于小程序组件的信息，谢谢。

**Comment by imcczy** [comment]
我碰到的有些小程序的wxml在app-service.js和page-frame.js都有存在，需要调用wuwxml把app-service.js里面的wxml解出来才行

**Comment by qwerty472123** [comment]
@imcczy app-service.js和page-frame.js内的wxml似乎是完全是重复的 但是似乎解出来内容不同 如果你知道的话 可否告知这两者的内容又什么联系呢？ 谢谢

**Comment by andy388** [comment]
@qwerty472123 不知道为何解出来的代码里面总是剩下一个包含xxx.ori.js这样的。。在 
`pages/specialtopic/views/index2/index.wxml.tem-floorTpl.ori.js`
[地址](https://pan.baidu.com/s/18oxy9UuBb4U6CKglmrMV5A)   密码：lrd9

**Comment by imcczy** [comment]
@qwerty472123 是否重复我现在出差不好确定，上一个可用的版本，需要把app-service.js里的wxml解出来才能用开发者工具调试

**Comment by qwerty472123** [comment]
@andy388 那似乎是微信的bug 😓
该包中将 `wx:key` 的值写为 `{{ item.id + '-' + goodsChunkIndex }}`
微信"编译"成了 `_2z(z,30,o6,oP,bO,gg,x5,'goodsChunk','goodsChunkIndex','{{ item.id + '-' + goodsChunkIndex }}')`
最后一项的结果是nan这是显然不对的，也恰好是我的脚本无法解析的
