### ISSUE TITLE
解压分包出错

### ISSUE THREAD

**Issue by reechou** [qwerty472123/wxappUnpacker#118]
May be this package is a subPackage which should be unpacked with -s=<MainDir>

解压分包还是出现这个错误 加了 MainDir
命令为：
node wuWxapkg.js -s=./f6de052da5316347d90f07ff05982386/ 85aa1bbc8634e3d4f9655d851b5ac62c.wxapkg

请问这个命令错在哪里

**Comment by qwerty472123** [comment]
这个命令暂不支持啊
加粗写在readme上了
# 当前功能如下（分包功能尚未完成！）
