### ISSUE TITLE
js 语法错误, return 写在了函数外面。

### ISSUE THREAD

**Issue by jk0011** [qwerty472123/wxappUnpacker#120]
vm.js:32
return new x;
^^^^^^

**SyntaxError: Illegal return statement**
    at new Script (vm.js:74:7)

**Comment by qwerty472123** [comment]
本项目使用Node.js正是因为它和wxapkg包内编译结果属于同种语言。
为了方便的解析包内内容，本项目通过简单字符串匹配截取包内脚本，通过“执行”的方式来解析（这里使用了VM2来阻止可能存在于包内的恶意代码被执行）。
你说遇到的问题是截取的脚本不对 是对版本的匹配有问题 **如无样例无法适配**
