### ISSUE TITLE
无法获取小程序源码包.wxapkg

### ISSUE THREAD

**Issue by fenglinxiu** [qwerty472123/wxappUnpacker#125]
现在不能通过你说的那种方式获取小程序源码包了，那个路径下找不到xx.wxapkg文件，还有其他办法吗？

**Comment by springrider** [comment]
android需要root才可以的.

**Comment by qwerty472123** [comment]
本项目不针对wxapkg获取、解包进行研究
相关内容仅照搬网上公开文章
