### ISSUE TITLE
分包那块有问题啊，无法指定主包路径

### ISSUE THREAD

**Issue by peng20017** [qwerty472123/wxappUnpacker#129]

**Comment by peng20017** [comment]
node wuWxapkg.js -s=C:\Users\Administrator\Desktop\dev\三\_326398222_11 C:\Users\Administrator\Desktop\dev\三\_335314004_11.wxapkg
不知道是不是我用法问题

**Comment by qwerty472123** [comment]
这功能压根没写呢... readme.md上也写了 
# （分包功能尚未完成！）
