### ISSUE TITLE
小程序插件破解还没有支持。怎么样把插件略过来解析这个小程序？

### ISSUE THREAD

**Issue by lhz1208** [qwerty472123/wxappUnpacker#131]
小程序插件破解还没有支持。怎么样把插件略过来解析这个小程序？

**Comment by xianhaosui** [comment]
D:\nodejs\wxappUnpacker\node_modules\vm2\lib\main.js:210
throw this._internal.Decontextify.value(e);
楼上是这个错吗？？

**Comment by qwerty472123** [comment]
本项目的目的在于基本正确的在微信小程序开发者工具上运行小程序，不会直接、提倡使用额外手工分析去实现 破解 小程序的任何内容（包括但不限于插件）
小程序插件与本身其他代码有一定的关系，如果需要分离部分代码需要手工阅读部分小程序包内js代码并修改之，如有关于各处js含义请参考 项目目录下 `*.md` 文件。

@xianhaosui 本程序报错信息仅供参考，导致同一错误的原因多种多样 错误信息本身不能说明任何问题 如有疑问请参考 项目目录下 `*.md` 文件。
