### ISSUE TITLE
小程序分包后unpacker不成功

### ISSUE THREAD

**Issue by shjshengok** [qwerty472123/wxappUnpacker#134]
程序的主包可以解压，但子包解压不了
附件上传一个子包示例
[rr.zip](https://github.com/qwerty472123/wxappUnpacker/files/2339211/rr.zip)

解压时报错：
wxappUnpacker\wxappUnpacker\wuWxapkg.js:104
        }else throw Error("This package is unrecognizable.\nMay be this package is a subPackage which should be unpacked with -s=<MainDir>.\nOtherwise, please decrypted every type of file by hand.")
              ^

Error: This package is unrecognizable.
May be this package is a subPackage which should be unpacked with -s=<MainDir>.
Otherwise, please decrypted every type of file by hand.

麻烦帮忙看下！

**Comment by qwerty472123** [comment]
这个功能没有完成 README.md上 写明了啊

**Comment by shjshengok** [comment]
好的，谢谢，还想请问下，你之前说的手动解包，其他都能解出来，但是wxss就是解不出来， node wuWxss.js，这个命令正确用法是怎样的？？我的分包里面只有page-frame.js，app-service.js，没看到wxss与page-frame.html之类的文件，麻烦了

**Comment by qwerty472123** [comment]
page-frame.html 不一定是这个名字 你可以根据内容分析
