### ISSUE TITLE
v0.6vv_20180522_fbi新的规则，还原wxml时Z的取值错误

### ISSUE THREAD

**Issue by CyrusLiu158** [qwerty472123/wxappUnpacker#135]
版本：v0.6vv_20180522_fbi

程序执行命令(可选):
wuWxml.js  -m ./page-frame.html

程序执行错误信息(如果反馈是抛出异常的错误，必填):
1、程序包执行 wuWxml.js， 356行code.lastIndexOf("if(path&&e_[path]){")报错，改成code.IndexOf("if(path&&e_[path]){")  可以继续执行

2、程序包生成wxml出现很多Empty值，如：
 <view class="Empty">
                <__textNode__></__textNode__>
  </view>

调试代码发现本包存在非$gwx_(\d)的情况，且z的取值不正确

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):

https://pan.baidu.com/s/1qj0QpQnr5g4MZQjAKhpoMw

[_-1805724530_25.wxapkg.zip](https://github.com/qwerty472123/wxappUnpacker/files/2340230/_-1805724530_25.wxapkg.zip)

其他：这个包是有插件的版本，在逐个文件调试

**Comment by qwerty472123** [comment]
含插件版本目前暂不支持，bug请自行处理
