### ISSUE TITLE
碰到有-webkit开头的样式时无法解析，包和正确的原样式文件都放在网盘里了

### ISSUE THREAD

**Issue by zjjzff1** [qwerty472123/wxappUnpacker#136]
链接: https://pan.baidu.com/s/1QIGX5VA0BeTlphxda2uLgQ 密码: s5wr
碰到有-webkit开头的样式时无法解析，包和正确的原样式文件都放在网盘里了，就看下home.wxss就行

**Comment by qwerty472123** [comment]
这是个feature去忽略所有微信自动生成的用来适配不同浏览器的css代码
由于信息丢失这里显然不能判断你原来有没有适配（或者是微信适配的）
需要时可把相关代码注释掉
