### ISSUE TITLE
反编译block if for key 同时出现，有错误

### ISSUE THREAD

**Issue by tosmq008** [qwerty472123/wxappUnpacker#14]
(如果你是要反馈 bug，请按以下格式书写 Issue )

程序执行命令(可选)：

程序执行错误信息（如果反馈是抛出异常的错误，必填）:

![image](https://user-images.githubusercontent.com/1542804/37885251-bd01552c-30e6-11e8-9511-1efecc935016.png)

![image](https://user-images.githubusercontent.com/1542804/37885238-ae08e7d8-30e6-11e8-9bf3-496d1bd94be9.png)

程序结果错误信息（如果反馈不是抛出异常的错误，必填，请尽可能详细描述）:

程序包地址（你所解压的程序包地址，可为网盘，也可直接上传，如果不愿意公开，请附上具体出错的文件）：
https://pan.baidu.com/s/1g3Y8_ZSR3vSAF2Rmn7pmHQ
[_-1773598078_93.wxapkg.zip](https://github.com/qwerty472123/wxappUnpacker/files/1846231/_-1773598078_93.wxapkg.zip)

其他附加内容：

经过处理反编译后的文件结论如下：
<block > 中出现 for 循环 和 key 的时候，if 判断会出现异常，不应该在 block 同一个层级
报错代码如下
```
<block wx:if="{{ssss}}"  wx:for="" wx:key="">
<view> </view>
</block>
```
修改如下可以运行
```
<block wx:if="{{ssss}}">
<view wx:for="" wx:key=""> </view>
</block>
```

**Comment by qwerty472123** [comment]
让我先吐槽一下：微信的编译器也太垃圾了吧

**Comment by qwerty472123** [comment]
看了下wx的逻辑是for/if在一起时默认for内有if，而很多时候我们是if内有for
另外还有if和elif之类的嵌套在一起导致的漏洞
已修复
