### ISSUE TITLE
err:  Error: Unknown init callee gz$gwx_x

### ISSUE THREAD

**Issue by febobo** [qwerty472123/wxappUnpacker#142]
node wuWxapkg.js xx.wxapkg 解压wxml 出错， 

![image](https://user-images.githubusercontent.com/9276376/45498483-aed12480-b7ac-11e8-8e7f-c9d7bf07c784.png)

_-1794825816_11.zip

**Comment by qwerty472123** [comment]
请提供样例文件

**Comment by febobo** [comment]
[_-1794825816_11.zip](https://github.com/qwerty472123/wxappUnpacker/files/2383459/_-1794825816_11.zip)
@qwerty472123 sorry ，没注意看上一个没传上去 ...

**Comment by qwerty472123** [comment]
请使用repo上最新的js文件来解包
