### ISSUE TITLE
编译后全是html了

### ISSUE THREAD

**Issue by jacksuc** [qwerty472123/wxappUnpacker#143]
我提供的程序包是v0.5vv_20180905，之前的都可以编译。现在编译出来全是html，不会是越用还越旧了吧。
[wanchejs.zip](https://github.com/qwerty472123/wxappUnpacker/files/2381647/wanchejs.zip)

**Comment by jacksuc** [comment]
> 我提供的程序包是v0.5vv_20180905，之前的都可以编译。现在编译出来全是html，不会是越用还越旧了吧。
> [wanchejs.zip](https://github.com/qwerty472123/wxappUnpacker/files/2381647/wanchejs.zip)

好像是版本升级和插件升级后，不再支持了。换了早期的版本也不行（插件没换）。

**Comment by jacksuc** [comment]
发现好多还是0.5的

**Comment by qwerty472123** [comment]
0.5 0.6我也不清楚是什么含义 总之看后面日期应该是不会错的

**Comment by qwerty472123** [comment]
看了一下应该是含插件的版本 把插件代码去除后是能够解析的 插件的支持目前我还没功夫 抱歉

**Comment by jacksuc** [comment]
> 看了一下应该是含插件的版本 把插件代码去除后是能够解析的 插件的支持目前我还没功夫 抱歉

如何除去插件呢。不是很清楚。工具目前也算是很方便了。非常感谢！！！

**Comment by qwerty472123** [comment]
> > 看了一下应该是含插件的版本 把插件代码去除后是能够解析的 插件的支持目前我还没功夫 抱歉
> 
> 如何除去插件呢。不是很清楚。工具目前也算是很方便了。非常感谢！！！

把js里requirePlugin definePlugin调用和插件生成的wxss(大概是第一个v0.*vv 到第二个v0.*vv之间的代码)删除

**Comment by jacksuc** [comment]
> > > 看了一下应该是含插件的版本 把插件代码去除后是能够解析的 插件的支持目前我还没功夫 抱歉
> > 
> > 
> > 如何除去插件呢。不是很清楚。工具目前也算是很方便了。非常感谢！！！
> 
> 把js里requirePlugin definePlugin调用和插件生成的wxss(大概是第一个v0.*vv 到第二个v0.*vv之间的代码)删除

好的，谢谢， 我试试。
