### ISSUE TITLE
error 依赖包都装了 uglify-es

### ISSUE THREAD

**Issue by zky1347888** [qwerty472123/wxappUnpacker#147]
node wuWxapkg.js
module.js:544
    throw err;
    ^

Error: Cannot find module 'uglify-es'
    at Function.Module._resolveFilename (module.js:542:15)

**Comment by qwerty472123** [comment]
引用包的相关问题自己解决或自己去相关包的地方问
你甚至可以用 js-beautify 来替代 Uglify-ES 在这里的作用
