### ISSUE TITLE
无法编译出wxss中的-webkit-background-clip: text;

### ISSUE THREAD

**Issue by xjd1123** [qwerty472123/wxappUnpacker#153]
无法编译出某些小程序wxss里面的-webkit-background-clip: text;
例如：
正常的：.pointIcon {
    background-clip: text;
    background: -webkit-linear-gradient(top,#FD8903,#FE2423);
    -webkit-text-fill-color: transparent;
    -webkit-background-clip: text;
}
我们编译出的：
.pointIcon {
    background-clip: text;
    background: -webkit-linear-gradient(top,#FD8903,#FE2423);
    -webkit-text-fill-color: transparent;
								  
}
缺少：-webkit-background-clip: text;

**Comment by xjd1123** [comment]
程序缓存包地址：http://wm.hirsch.cn/tbk.zip

**Comment by qwerty472123** [comment]
该程序会自动省略一些 由微信开发者工具自动生成的 -webkit 头属性
例如有特定属性 A 会自动生成属性 -webkit-A
当然这里具体源码里有没有 -webkit-A 的信息被丢失而无法还原
如果为了考虑最大兼容性 把用于自动省略的代码注释掉即可
