### ISSUE TITLE
  子域的图片资源能编译出来，主域的没有res目录是什么情况啊，

### ISSUE THREAD

**Issue by zbbjgy** [qwerty472123/wxappUnpacker#154]
(如果你是要反馈 bug, 请按以下格式书写 Issue; 如果你遇到的是 Node.js 使用问题, 请尽可能依赖搜索引擎解决问题; 任何对某类小程序包的适配问题都应提供 wxapkg 程序包，否则直接 Close 处理; 提交前请确认 wxapkg 程序包版本不小于 v0.6vv_20180111_fbi (直接用文本编辑器打开 wxapkg包搜索 v0.6vv 或 v0.5vv 即可查到，注意版本大小主要比较的是日期), 旧版本不提供支持, 相关 Issue 直接 Close 处理。)

程序执行命令(可选):

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
复制到这里
```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):

其他附加内容:

**Comment by qwerty472123** [comment]
请按要求发 关于 bug 的 issue

**Comment by zbbjgy** [comment]
程序执行命令： node wuWxapkg.js  _-340713722_6.wxapkg 

命令结果信息： 
Unpack file _-340713722_6.wxapkg...

Header info:
  firstMark: 0xbe
  unknownInfo:  0
  infoListLength:  372
  dataLength:  2951969
  lastMark: 0xed

File list info:
  fileCount:  7
{ name: '/cakeSub/res/raw-assets/fonts/number01.3b5d3.png',
  off: 386,
  size: 3295 }
{ name: '/cakeSub/res/raw-assets/textures/rank/AutoAtlas-1.47dce.png',
  off: 3681,
  size: 60844 }
{ name: '/cakeSub/res/raw-internal/image/default_scrollbar_vertical_bg.4bb41.png',
  off: 64525,
  size: 206 }
{ name: '/cakeSub/res/raw-internal/image/default_scrollbar_vertical.71821.png',
  off: 64731,
  size: 181 }
{ name: '/app-config.json', off: 64912, size: 178 }
{ name: '/game.js', off: 65090, size: 1530948 }
{ name: '/subContext.js', off: 1596038, size: 1356317 }
Saving files...
Unpack done.
Split game.js and rewrite game.json...
Found subContext, splitting it...
Splitting "/Users/zhzc/mySelfproject/wxappUnpacker-0.3/_-340713722_6/game.js" done.
Splitting "/Users/zhzc/mySelfproject/wxappUnpacker-0.3/_-340713722_6/subContext.js" done.
Split and rewrite done.
Total use: 6595.521ms
localhost:wxappUnpacker-0.3 zhzc$ 
### ### 

程序包链接：
链接: https://pan.baidu.com/s/1R7hOqFhFmqM8QbHiosBGdw 提取码: rp9z

附言：
麻烦老师看一下。受教了。

**Comment by qwerty472123** [comment]
抱歉 前几天没有看到
可以重发一份吗

**Comment by qwerty472123** [comment]
没有目前可访问的wxapkg包 先close了
按程序输出来看包中并没有你想要的res目录，很可能相关文件在其他包中
