### ISSUE TITLE
请问有没有讨论群之类的呀？？

### ISSUE THREAD

**Issue by yorick520** [qwerty472123/wxappUnpacker#158]
请问是否有相关讨论群呀？问题太多了，咨询也咨询不了

**Comment by 36304099** [comment]
同问

**Comment by qwerty472123** [comment]
没有。
这就是我闲余时间写着玩的项目。有相关需求的请寻找别的项目或认真阅读DETAILS.md后自行分析或直接自行分析解决。
当然如果你们愿意提供样例，我可以试着分析，但对分析结果不作任何保证。
