### ISSUE TITLE
当前版本wxml 解析

### ISSUE THREAD

**Issue by superzys** [qwerty472123/wxappUnpacker#160]
现在解析wxml 出来是wxml.ori.js 。看了老版本的wxapkg 和新版本的对比。 page-frame.html格式变了。是要重新整理下wuWxml.js 吧?

**Comment by qwerty472123** [comment]
wxml.ori.js 并不是解析结果 而是解析失败的后提供的辅助调试信息....
可以提供一个你说的新版本吗

**Comment by superzys** [comment]
可能是环境问题。 我用了家里的 win电脑 确实可以。*_*  容我对比系统环境

**Comment by qwerty472123** [comment]
那就先关闭本issue吧

**Comment by JackWe** [comment]
![image](https://user-images.githubusercontent.com/17582816/58925484-47b03180-877a-11e9-8195-b28987bae51b.png)
大神，同样遇到此问题
