### ISSUE TITLE
解析部分XMl文件存在bug，我已整理好资料，管理员看下

### ISSUE THREAD

**Issue by zjjzff1** [qwerty472123/wxappUnpacker#161]
链接：https://pan.baidu.com/s/1Px7uClEyqU3DtZUL6fapTQ 密码：5c65

里面有一个时间组件datetime-picker，解包后的XML文件是空的，正确的XML文件我也要到了，全部放在了网盘内，管理员对比下看看，是否解析xml文件有bug

**Comment by zjjzff1** [comment]
另外插件的json组件会丢失  "usingComponents": {
xxx
  }

这个信息

**Comment by qwerty472123** [comment]
我这里解包后 components\datetime-picker 目录下的xml和你提供原始版本的基本一致啊
第二的问题在 #117 中提到 现已初步解决
