### ISSUE TITLE
解压个别小程序报错

### ISSUE THREAD

**Issue by qq282256882** [qwerty472123/wxappUnpacker#162]
[_-1112911339_5.zip]
(https://github.com/qwerty472123/wxappUnpacker/files/2492625/_-1112911339_5.zip)

程序执行命令
node D:\wechat\pojie\wxappUnpacker-master\wuWxapkg.js D:\wechat\pojie\renminribao\_-1112911339_5.wxapkg

程序执行错误信息
Unpack file D:\wechat\pojie\renminribao\_-1112911339_5.wxapkg...

Header info:
  firstMark: 0xbe
  unknownInfo:  0
  infoListLength:  529
  dataLength:  190168
  lastMark: 0xed

File list info:
  fileCount:  16
{ name: '/resources/1_2.png', off: 543, size: 933 }
{ name: '/resources/1.png', off: 1476, size: 926 }
{ name: '/resources/2_2.png', off: 2402, size: 973 }
{ name: '/resources/2.png', off: 3375, size: 960 }
{ name: '/resources/3_2.png', off: 4335, size: 2249 }
{ name: '/resources/3.png', off: 6584, size: 2116 }
{ name: '/resources/closed.png', off: 8700, size: 2131 }
{ name: '/resources/group_6.png', off: 10831, size: 10307 }
{ name: '/app-config.json', off: 21138, size: 5687 }
{ name: '/app-service.js', off: 26825, size: 52771 }
{ name: '/pages/detail/detail.html', off: 79596, size: 1143 }
{ name: '/pages/menu/menu.html', off: 80739, size: 1471 }
{ name: '/pages/paper/paper.html', off: 82210, size: 702 }
{ name: '/pages/template/datepicker/datepicker-template.html',
  off: 82912,
  size: 900 }
{ name: '/wxParse/wxParse.html', off: 83812, size: 3686 }
{ name: '/page-frame.html', off: 87498, size: 103213 }
Saving files...
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...
Splitting "D:\wechat\pojie\renminribao\_-1112911339_5\app-service.js" done.

D:\wechat\pojie\wxappUnpacker-master\node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
ReferenceError: x is not defined
    at vm.js:2695:10
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at VM.run (D:\wechat\pojie\wxappUnpacker-master\node_modules\vm2\lib\main.js:204:72)
    at z (D:\wechat\pojie\wxappUnpacker-master\wuWxml.js:366:7)
    at z (D:\wechat\pojie\wxappUnpacker-master\wuRestoreZ.js:244:17)
    at catchZ (D:\wechat\pojie\wxappUnpacker-master\wuRestoreZ.js:28:2)
    at getZ (D:\wechat\pojie\wxappUnpacker-master\wuRestoreZ.js:244:2)
    at wu.get.code (D:\wechat\pojie\wxappUnpacker-master\wuWxml.js:354:3)
    at ioLimit.runWithCb (D:\wechat\pojie\wxappUnpacker-master\wuLib.js:80:8)
    at agent (D:\wechat\pojie\wxappUnpacker-master\wuLib.js:54:14)

**Comment by qq282256882** [comment]
[_-1112911339_5.zip](https://github.com/qwerty472123/wxappUnpacker/files/2492621/_-1112911339_5.zip)

**Comment by qwerty472123** [comment]
版本过低(`v0.6vv_20170919_fbi_wxs`) 不予支持

**Comment by qq282256882** [comment]
已自行研究解出

发自我的 iPhone

**Comment by qwerty472123** [comment]
> 已自行研究解出 发自我的 iPhone
> […](#)
> 在 2018年10月19日，下午12:21，Steve-Tod ***@***.***> 写道： 我的也是一模一样的错误，求解😂 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

终于有人肯不伸手研究了😂
