### ISSUE TITLE
你好现在这种分包也不能解了麻烦看看吧

### ISSUE THREAD

**Issue by caominkeji** [qwerty472123/wxappUnpacker#166]
解不出wxml的

[heika.zip](https://github.com/qwerty472123/wxappUnpacker/files/2514341/heika.zip)

**Comment by qwerty472123** [comment]
可以提供相应的主包吗？

**Comment by caominkeji** [comment]
好的
[heika.zip](https://github.com/qwerty472123/wxappUnpacker/files/2517599/heika.zip)

**Comment by qwerty472123** [comment]
@caominkeji 你确定这是对应的主包吗？这个包根本就没有子包啊

**Comment by qwerty472123** [comment]
先根据我的猜测更新一次吧

**Comment by caominkeji** [comment]
好的谢谢了

**Comment by qwerty472123** [comment]
暂时标记为解决吧
