### ISSUE TITLE
烦大佬看下这个包

### ISSUE THREAD

**Issue by asiacny** [qwerty472123/wxappUnpacker#167]
表面看很简单的一个程序，解码后却发现.wxml文件内都是empty空定义，查看page-frame.html内是有相应中文定义的，不知是否因可能有插件的问题。(url)
[a.zip](https://github.com/qwerty472123/wxappUnpacker/files/2522906/a.zip)

**Comment by qwerty472123** [comment]
版本过低(v0.6vv_20171208_cua_xc)本项目不支持

**Comment by asiacny** [comment]
抱歉，没注意日期，还以为版本号优先，谢谢
