### ISSUE TITLE
解出来的小程序页面wxml文件为 .wxml.ori.js后缀，请问怎么解决

### ISSUE THREAD

**Issue by shidiyanmo** [qwerty472123/wxappUnpacker#168]
发表 Issue 前请仔细阅读以下内容：

1. 如果你是要反馈 bug, 请按以下`模板`书写 Issue;
2. 如果你遇到的是 Node.js 使用问题, 请尽可能依赖搜索引擎解决问题;
3. 遇到包依赖问题，请联系对应项目;
4. 任何对某类小程序包的适配问题都应提供 wxapkg 程序包，否则直接 Close 处理;
5. 提交前请确认 wxapkg 程序包版本不小于 v0.6vv_20180111_fbi (直接用文本编辑器打开 wxapkg包搜索 v0.6vv 或 v0.5vv 即可查到，注意版本大小主要比较的是日期), 旧版本不提供支持, 相关 Issue 直接 Close 处理;
6. 直接分包和直接处理含插件的包两个功能暂不支持, 请勿重复发表 Issue, 新样例可在已存在的 Issue 下提出;
7. 请不要在其他 Issue 下发表与该 Issue 无关的回复, 否则将有可能被删除。

模板内容如下：

程序执行命令(可选):

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
复制到这里
```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):

其他附加内容:

**Comment by shidiyanmo** [comment]
`var f37=_n('view')
var c47=_mz(z,'form',['bindreset',2,'bindsubmit',1,'reportSubmit',2],[],e,s,gg)
var h57=_n('view')
_rz(z,h57,'class',5,e,s,gg)
var o67=_n('view')
_rz(z,o67,'style',6,e,s,gg)
var c77=_n('view')
_rz(z,c77,'class',7,e,s,gg)
var o87=_oz(z,8,e,s,gg)`

**Comment by qwerty472123** [comment]
请安要求发Issue
