### ISSUE TITLE
wxapkg程序包解包后无page-frame.html，子目录出现wxml.ori.js

### ISSUE THREAD

**Issue by ayackcn** [qwerty472123/wxappUnpacker#171]
一、
v0.5vv_20180810_syb_zp
err:  Error: Unknown init callee gz$gwx_49

wxapkg程序包解包后无page-frame.html
子目录无 xxx.wxml，而是出现 xxx.wxml.ori.js

    at ioLimit.runWithCb (C:\Users\Administrator\Desktop\新建文件夹 (2)\tools\wx
appUnpacker-master\wuLib.js:80:8)
    at agent (C:\Users\Administrator\Desktop\新建文件夹 (2)\tools\wxappUnpacker-
master\wuLib.js:54:14)
Decompile ./pages/wx-cropper/wx-cropper.wxml...
error on ./pages/wx-cropper/wx-cropper.wxml
err:  Error: Unknown init callee gz$gwx_58
    at analyze (C:\Users\Administrator\Desktop\新建文件夹 (2)\tools\wxappUnpacke
r-master\wuWxml.js:136:22)

包链接: https://pan.baidu.com/s/1TRTiK-Y-e6bF2ExkBPOGVA
提取码: t2iw

二：
v0.6vv_20180516_fbi
5月份下载的wxappUnpacker工具，解另一个a.wxapkg，无问题，新版本wxappUnpacker（2018.11.08下载）解包，会出现以上问题。

**Comment by qwerty472123** [comment]
我在本地测试你提供的包 解包正常，无报错信息，未产生*.ori.js文件 未能复现任何问题
