### ISSUE TITLE
报了个错。不知道是啥原因

### ISSUE THREAD

**Issue by jacksuc** [qwerty472123/wxappUnpacker#173]
发表 Issue 前请仔细阅读以下内容：

程序执行命令(可选):$ node wuWxapkg.js youhuiq.wxapkg

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
Split app-service.js and make up configs & wxss & wxml & wxs...

D:\Program Files\wxappUnpacker\node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
SyntaxError: Unexpected token }

```

[youhuiq.zip](https://github.com/qwerty472123/wxappUnpacker/files/2575440/youhuiq.zip)

**Comment by jacksuc** [comment]
单独编译样式的时候也出错了。
`$ node wuWxss.js page-frame.js
D:\Program Files\wxappUnpacker\wuLib.js:96
                        if(err)throw Error("Scan dir error: "+err);
                               ^

Error: Scan dir error: Error: ENOTDIR: not a directory, scandir 'D:\Program File
s\wxappUnpacker\page-frame.js'
    at ioLimit.runWithCb (D:\Program Files\wxappUnpacker\wuLib.js:96:17)
    at agent (D:\Program Files\wxappUnpacker\wuLib.js:54:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
`

[page-frame.zip](https://github.com/qwerty472123/wxappUnpacker/files/2583381/page-frame.zip)

**Comment by qwerty472123** [comment]
该包中含有插件 暂不支持
请正确使用wxss相关命令 `node wuWxss.js <dirs...>`，注意参数为文件夹。
当然，对于有插件的包，需要删除插件部分代码才能成功运行wxss。

**Comment by jacksuc** [comment]
> 该包中含有插件 暂不支持
> 请正确使用wxss相关命令 `node wuWxss.js <dirs...>`，注意参数为文件夹。
> 当然，对于有插件的包，需要删除插件部分代码才能成功运行wxss。

好的
