### ISSUE TITLE
反编译代码文件 不是默认格式

### ISSUE THREAD

**Issue by jianwangzhan** [qwerty472123/wxappUnpacker#174]
发表 Issue 前请仔细阅读以下内容：

1. 如果你是要反馈 bug, 请按以下`模板`书写 Issue;
 
4. 任何对某类小程序包的适配问题都应提供 wxapkg 程序包，否则直接 Close 处理;
5. 提交前请确认 wxapkg 程序包版本不小于 v0.6vv_20180111_fbi (直接用文本编辑器打开 wxapkg包搜索 v0.6vv 或 v0.5vv 即可查到，注意版本大小主要比较的是日期), 旧版本不提供支持, 相关 Issue 直接 Close 处理;
/*v0.5vv_20180905_syb_scopedata*/global.__wcc_version__='v0.5vv_20180905_syb_scopedata'; 
6. 直接分包和直接处理含插件的包两个功能暂不支持, 请勿重复发表 Issue, 新样例可在已存在的 Issue 下提出;
7. 请不要在其他 Issue 下发表与该 Issue 无关的回复, 否则将有可能被删除。

模板内容如下：
编译出来 全是html文件
程序执行命令(可选):
node wuWxapkg.js 包文件名
程序执行错误信息(如果反馈是抛出异常的错误，必填):

{ name: '/images/icon/icon_11.png', off: 906748, size: 3765 }
{ name: '/images/icon/icon_12.png', off: 910513, size: 4711 }
{ name: '/images/icon/icon_13.png', off: 915224, size: 4871 }
{ name: '/images/icon/icon_14.png', off: 920095, size: 4769 }
{ name: '/images/icon/icon_15.png', off: 924864, size: 5221 }
{ name: '/images/icon/icon_16.png', off: 930085, size: 5204 }
{ name: '/images/icon/icon_2.png', off: 935289, size: 5508 }
{ name: '/images/icon/icon_3.png', off: 940797, size: 3275 }
{ name: '/images/icon/icon_4.png', off: 944072, size: 3945 }
{ name: '/images/icon/icon_5.png', off: 948017, size: 4933 }
{ name: '/images/icon/icon_6.png', off: 952950, size: 4231 }
{ name: '/images/icon/icon_7.png', off: 957181, size: 4654 }
{ name: '/images/icon/icon_8.png', off: 961835, size: 4761 }
{ name: '/images/icon/icon_9.png', off: 966596, size: 3733 }
{ name: '/images/icon/icon_practice.png',
  off: 970329,
  size: 609 }
{ name: '/images/icon/icon_practice1.png',
  off: 970938,
  size: 291 }
{ name: '/images/image-avatar.png', off: 971229, size: 4916 }
{ name: '/images/image-good.png', off: 976145, size: 2084 }
{ name: '/images/main_homepage.png', off: 978229, size: 3552 }
{ name: '/images/main_homepage_selected.png',
  off: 981781,
  size: 3354 }
{ name: '/images/main_mine.png', off: 985135, size: 4371 }
{ name: '/images/main_mine_selected.png',
  off: 989506,
  size: 3994 }
{ name: '/images/my.png', off: 993500, size: 1490 }
{ name: '/images/my_gray.png', off: 994990, size: 3528 }
{ name: '/images/nothing.png', off: 998518, size: 11309 }
{ name: '/images/order/icon-baoxian.png',
  off: 1009827,
  size: 7129 }
{ name: '/images/order/icon-daishou.png',
  off: 1016956,
  size: 7050 }
{ name: '/images/order/icon-moniche.png',
  off: 1024006,
  size: 6446 }
{ name: '/images/order/icon-order.png',
  off: 1030452,
  size: 22203 }
{ name: '/images/order/order-detail-bg.png',
  off: 1052655,
  size: 73085 }
{ name: '/images/order/order-detail-delimiter.png',
  off: 1125740,
  size: 2265 }
{ name: '/images/question_set/1_03.png',
  off: 1128005,
  size: 3426 }
{ name: '/images/question_set/1_05.png',
  off: 1131431,
  size: 6448 }
{ name: '/images/question_set/1_07.png',
  off: 1137879,
  size: 5551 }
{ name: '/images/question_set/1_09.png',
  off: 1143430,
  size: 7123 }
{ name: '/images/question_set/map.png',
  off: 1150553,
  size: 2339 }
{ name: '/images/remove.png', off: 1152892, size: 2056 }
{ name: '/images/right.svg', off: 1154948, size: 1931 }
{ name: '/images/select_d.png', off: 1156879, size: 1119 }
{ name: '/images/signup.png', off: 1157998, size: 716 }
{ name: '/images/signup_gray.png', off: 1158714, size: 825 }
{ name: '/images/start-image1.jpg', off: 1159539, size: 52401 }
{ name: '/images/tuijian.png', off: 1211940, size: 1951 }
{ name: '/images/warn.png', off: 1213891, size: 2378 }
{ name: '/images/wrong.png', off: 1216269, size: 29835 }
{ name: '/app-config.json', off: 1246104, size: 26074 }
{ name: '/app-service.js', off: 1272178, size: 407174 }
{ name: '/__wx__/functional-page.html', off: 1679352, size: 321 }
{ name: '/__wx__/open-api-redirecting-page.html',
  off: 1679673,
  size: 341 }
{ name: '/pages/QRbind/index.html', off: 1680014, size: 1916 }
{ name: '/pages/banner/coupon/index.html',
  off: 1681930,
  size: 782 }
{ name: '/pages/banner/drill/drill.html',
  off: 1682712,
  size: 1775 }
{ name: '/pages/banner/drill_instruction/drill_instruction.html',
  off: 1684487,
  size: 1028 }
{ name: '/pages/banner/drill_previous/drill_previous.html',
  off: 1685515,
  size: 742 }
{ name: '/pages/banner/drive_discount/drive_discount.html',
  off: 1686257,
  size: 3662 }
{ name: '/pages/banner/free_study/free_study.html',
  off: 1689919,
  size: 4456 }
{ name: '/pages/banner/insurance/insurance.html',
  off: 1694375,
  size: 2739 }
{ name: '/pages/banner/insurance_explain/insurance_explain.html',
  off: 1697114,
  size: 373 }
{ name: '/pages/banner/myticket/index.html',
  off: 1697487,
  size: 518 }
{ name: '/pages/exam/appraiseRoad/index.html',
  off: 1698005,
  size: 904 }
{ name: '/pages/exam/carKnowledge/index.html',
  off: 1698909,
  size: 508 }
{ name: '/pages/exam/carKnowledgeDesc/index.html',
  off: 1699417,
  size: 613 }
{ name: '/pages/exam/doExercise/index.html',
  off: 1700030,
  size: 32770 }
{ name: '/pages/exam/drive_score/drive_score.html',
  off: 1732800,
  size: 1722 }
{ name: '/pages/exam/easyFail/index.html',
  off: 1734522,
  size: 1918 }
{ name: '/pages/exam/easyFailDetail/index.html',
  off: 1736440,
  size: 1222 }
{ name: '/pages/exam/examContent/index.html',
  off: 1737662,
  size: 1372 }
{ name: '/pages/exam/examRoad/index.html',
  off: 1739034,
  size: 1159 }
{ name: '/pages/exam/iconexercise/iconDetail.html',
  off: 1740193,
  size: 394 }
{ name: '/pages/exam/iconexercise/iconSkill.html',
  off: 1740587,
  size: 360 }
{ name: '/pages/exam/iconexercise/iconexercise.html',
  off: 1740947,
  size: 572 }
{ name: '/pages/exam/iconexercise/index.html',
  off: 1741519,
  size: 417 }
{ name: '/pages/exam/imiBillingRules/index.html',
  off: 1741936,
  size: 542 }
{ name: '/pages/exam/imitateCar/index.html',
  off: 1742478,
  size: 2200 }
{ name: '/pages/exam/index.html', off: 1744678, size: 4805 }
{ name: '/pages/exam/myWrongQuestions/index.html',
  off: 1749483,
  size: 3711 }
{ name: '/pages/exam/question_set/question_set.html',
  off: 1753194,
  size: 2464 }
{ name: '/pages/exam/roadDetail/index.html',
  off: 1755658,
  size: 2264 }
{ name: '/pages/exam/simulated/index.html',
  off: 1757922,
  size: 1821 }
{ name: '/pages/exam/specialExercise/index.html',
  off: 1759743,
  size: 3745 }
{ name: '/pages/my/aboutus/feedback.html',
  off: 1763488,
  size: 896 }
{ name: '/pages/my/aboutus/index.html', off: 1764384, size: 645 }
{ name: '/pages/my/bind/bind.html', off: 1765029, size: 903 }
{ name: '/pages/my/bind/index.html', off: 1765932, size: 525 }
{ name: '/pages/my/bindSchool/index.html',
  off: 1766457,
  size: 356 }
{ name: '/pages/my/coupon/index.html', off: 1766813, size: 1147 }
{ name: '/pages/my/examPayment/addCoach/index.html',
  off: 1767960,
  size: 536 }
{ name: '/pages/my/examPayment/examPayment.html',
  off: 1768496,
  size: 8800 }
{ name: '/pages/my/examPayment/selectCoach/index.html',
  off: 1777296,
  size: 744 }
{ name: '/pages/my/imitateResult/index.html',
  off: 1778040,
  size: 384 }
{ name: '/pages/my/imitateResultDesc/index.html',
  off: 1778424,
  size: 391 }
{ name: '/pages/my/index.html', off: 1778815, size: 5887 }
{ name: '/pages/my/myCoach/index.html', off: 1784702, size: 344 }
{ name: '/pages/my/myEvaluate/index.html',
  off: 1785046,
  size: 344 }
{ name: '/pages/my/order/applyclaim/applyclaim.html',
  off: 1785390,
  size: 1042 }
{ name: '/pages/my/order/freedetail.html',
  off: 1786432,
  size: 1685 }
{ name: '/pages/my/order/order.html', off: 1788117, size: 3022 }
{ name: '/pages/my/order/orderDetail/orderDetail.html',
  off: 1791139,
  size: 2300 }
{ name: '/pages/my/order/signature/signature.html',
  off: 1793439,
  size: 345 }
{ name: '/pages/my/order/userIdentify/userIdentify.html',
  off: 1793784,
  size: 357 }
{ name: '/pages/my/register/index.html',
  off: 1794141,
  size: 633 }
{ name: '/pages/search/index.html', off: 1794774, size: 335 }
{ name: '/pages/search/labledesc/index.html',
  off: 1795109,
  size: 692 }
{ name: '/pages/signup/agreement/index.html',
  off: 1795801,
  size: 412 }
{ name: '/pages/signup/appraise/index.html',
  off: 1796213,
  size: 1139 }
{ name: '/pages/signup/appraise/write.html',
  off: 1797352,
  size: 2025 }
{ name: '/pages/signup/classdesc/index.html',
  off: 1799377,
  size: 928 }
{ name: '/pages/signup/coach/coach.html',
  off: 1800305,
  size: 291 }
{ name: '/pages/signup/coachdesc/index.html',
  off: 1800596,
  size: 924 }
{ name: '/pages/signup/customize/index.html',
  off: 1801520,
  size: 355 }
{ name: '/pages/signup/imitateCar/index.html',
  off: 1801875,
  size: 352 }
{ name: '/pages/signup/index.html', off: 1802227, size: 1440 }
{ name: '/pages/signup/list/classlist.html',
  off: 1803667,
  size: 401 }
{ name: '/pages/signup/list/coachlist.html',
  off: 1804068,
  size: 401 }
{ name: '/pages/signup/list/fieldlist.html',
  off: 1804469,
  size: 401 }
{ name: '/pages/signup/list/imagelist.html',
  off: 1804870,
  size: 504 }
{ name: '/pages/signup/prospectus/index.html',
  off: 1805374,
  size: 352 }
{ name: '/pages/signup/school/school.html',
  off: 1805726,
  size: 351 }
{ name: '/pages/signup/schooldesc/index.html',
  off: 1806077,
  size: 4992 }
{ name: '/pages/signup/select/coachSelect.html',
  off: 1811069,
  size: 362 }
{ name: '/pages/signup/select/select.html',
  off: 1811431,
  size: 351 }
{ name: '/pages/signup/template/template.html',
  off: 1811782,
  size: 359 }
{ name: '/pages/startPage/index.html', off: 1812141, size: 638 }
{ name: '/page-frame.html', off: 1812779, size: 730316 }
Saving files...
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...

D:\wxappUnpacker-master\node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
SyntaxError: Unexpected token }
    at VMScript.compile (D:\wxappUnpacker-master\node_modules\vm2\lib\main.js:78
:20)
    at VM.run (D:\wxappUnpacker-master\node_modules\vm2\lib\main.js:204:52)
    at wu.get.code (D:\wxappUnpacker-master\wuJs.js:30:6)
    at ioLimit.runWithCb (D:\wxappUnpacker-master\wuLib.js:80:8)
    at agent (D:\wxappUnpacker-master\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
 

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):
https://pan.baidu.com/s/1GQIFyD5bH15HZA1BxTxVlQ

**Comment by qwerty472123** [comment]
该包中含有插件，暂不支持

**Comment by jianwangzhan** [comment]
请问qwerty472123大神 什么时候可以能支持呢？

**Comment by qwerty472123** [comment]
反正我寒假前是不可能写的。需要等待时间的上界我不能保证
