### ISSUE TITLE
app.json增加了 "navigateToMiniProgramAppIdList

### ISSUE THREAD

**Issue by zjjzff1** [qwerty472123/wxappUnpacker#175]
大牛，app.json增加了一个字段，就是跳转到其他程序，会有 "navigateToMiniProgramAppIdList：【appid】"这个字段，请更新下

**Comment by qwerty472123** [comment]
请问可否提供一个有该字段的小程序包？

**Comment by zjjzff1** [comment]
测试正常，可以解析出这个字段了。群主有空加我微qyswjdr

**Comment by tpcoder998** [comment]
您好,请问能增加带插件的小程序wxapkg包的解包么。

**Comment by tpcoder998** [comment]
@qwerty472123 大牛   请问可以增加带小程序插件的 wxapkg包的解析么   或者付费单独求。
