### ISSUE TITLE
编译出来 全是html文件

### ISSUE THREAD

**Issue by jdevsean** [qwerty472123/wxappUnpacker#176]
编译出来 全是html文件
程序执行命令(可选):
node wuWxapkg.js 包文件名
PS C:\Users\Biao\Desktop\小程序包\wxappUnpacker-master> node wuWxapkg.js _1360141122_9.wxapkg
Unpack file _1360141122_9.wxapkg...

Header info:
  firstMark: 0xbe
  unknownInfo:  0
  infoListLength:  3872
  dataLength:  1389363
  lastMark: 0xed

File list info:
  fileCount:  80
{ name: '/images/icon_accept.png', off: 3886, size: 278 }
{ name: '/images/icon_acceptinvite.png', off: 4164, size: 2657 }
{ name: '/images/icon_add_event.png', off: 6821, size: 2901 }
{ name: '/images/icon_address.png', off: 9722, size: 2751 }
{ name: '/images/icon_arrow.png', off: 12473, size: 601 }
{ name: '/images/icon_checkbox_off.png', off: 13074, size: 644 }
{ name: '/images/icon_checkbox_on.png', off: 13718, size: 766 }
{ name: '/images/icon_circle.png', off: 14484, size: 9673 }
{ name: '/images/icon_curve.png', off: 24157, size: 1342 }
{ name: '/images/icon_edit.png', off: 25499, size: 1399 }
{ name: '/images/icon_empty.png', off: 26898, size: 7868 }
{ name: '/images/icon_invite.png', off: 34766, size: 2096 }
{ name: '/images/icon_loading.png', off: 36862, size: 5956 }
{ name: '/images/icon_location_red.png', off: 42818, size: 614 }
{ name: '/images/icon_location.png', off: 43432, size: 846 }
{ name: '/images/icon_main.png', off: 44278, size: 721 }
{ name: '/images/icon_me.png', off: 44999, size: 818 }
{ name: '/images/icon_more.png', off: 45817, size: 381 }
{ name: '/images/icon_navigation.png', off: 46198, size: 540 }
{ name: '/images/icon_no_feeds.png', off: 46738, size: 17494 }
{ name: '/images/icon_opinion.png', off: 64232, size: 1071 }
{ name: '/images/icon_participant.png', off: 65303, size: 883 }
{ name: '/images/icon_personnel.png', off: 66186, size: 1884 }
{ name: '/images/icon_preview.png', off: 68070, size: 713 }
{ name: '/images/icon_remind_gray.png', off: 68783, size: 1618 }
{ name: '/images/icon_remind.png', off: 70401, size: 1885 }
{ name: '/images/icon_select_none.png', off: 72286, size: 644 }
{ name: '/images/icon_select.png', off: 72930, size: 449 }
{ name: '/images/icon_service.png', off: 73379, size: 2873 }
{ name: '/images/icon_success.png', off: 76252, size: 3315 }
{ name: '/images/icon_time.png', off: 79567, size: 1821 }
{ name: '/images/icon_version.png', off: 81388, size: 2903 }
{ name: '/images/icon_voice.png', off: 84291, size: 1122 }
{ name: '/images/templates/template_1301_detail_head.png',
  off: 85413,
  size: 39865 }
{ name: '/images/templates/template_1301_edit_head.png',
  off: 125278,
  size: 40573 }
{ name: '/images/templates/template_1301_index_head.png',
  off: 165851,
  size: 30378 }
{ name: '/images/templates/template_1301_template_head.png',
  off: 196229,
  size: 20269 }
{ name: '/images/templates/template_1302_detail_head.png',
  off: 216498,
  size: 38941 }
{ name: '/images/templates/template_1302_edit_head.png',
  off: 255439,
  size: 38906 }
{ name: '/images/templates/template_1302_index_head.png',
  off: 294345,
  size: 27805 }
{ name: '/images/templates/template_1302_template_head.png',
  off: 322150,
  size: 19636 }
{ name: '/images/templates/template_1303_detail_head.png',
  off: 341786,
  size: 62033 }
{ name: '/images/templates/template_1303_edit_head.png',
  off: 403819,
  size: 61483 }
{ name: '/images/templates/template_1303_index_head.png',
  off: 465302,
  size: 39469 }
{ name: '/images/templates/template_1303_template_head.png',
  off: 504771,
  size: 25429 }
{ name: '/images/templates/template_1304_detail_head.png',
  off: 530200,
  size: 31446 }
{ name: '/images/templates/template_1304_edit_head.png',
  off: 561646,
  size: 31382 }
{ name: '/images/templates/template_1304_index_head.png',
  off: 593028,
  size: 23584 }
{ name: '/images/templates/template_1304_template_head.png',
  off: 616612,
  size: 16918 }
{ name: '/images/templates/template_1305_detail_head.png',
  off: 633530,
  size: 48112 }
{ name: '/images/templates/template_1305_edit_head.png',
  off: 681642,
  size: 46246 }
{ name: '/images/templates/template_1305_index_head.png',
  off: 727888,
  size: 36759 }
{ name: '/images/templates/template_1305_template_head.png',
  off: 764647,
  size: 23909 }
{ name: '/images/templates/template_1306_detail_head.png',
  off: 788556,
  size: 39541 }
{ name: '/images/templates/template_1306_edit_head.png',
  off: 828097,
  size: 39951 }
{ name: '/images/templates/template_1306_index_head.png',
  off: 868048,
  size: 29848 }
{ name: '/images/templates/template_1306_template_head.png',
  off: 897896,
  size: 20941 }
{ name: '/images/templates/template_1307_detail_head.png',
  off: 918837,
  size: 53683 }
{ name: '/images/templates/template_1307_edit_head.png',
  off: 972520,
  size: 53631 }
{ name: '/images/templates/template_1307_index_head.png',
  off: 1026151,
  size: 35448 }
{ name: '/images/templates/template_1307_template_head.png',
  off: 1061599,
  size: 21554 }
{ name: '/images/templates/template_1308_detail_head.png',
  off: 1083153,
  size: 37245 }
{ name: '/images/templates/template_1308_edit_head.png',
  off: 1120398,
  size: 36412 }
{ name: '/images/templates/template_1308_index_head.png',
  off: 1156810,
  size: 28221 }
{ name: '/images/templates/template_1308_template_head.png',
  off: 1185031,
  size: 19120 }
{ name: '/app-config.json', off: 1204151, size: 1969 }
{ name: '/app-service.js', off: 1206120, size: 84612 }
{ name: '/components/DatePicker/datePicker.html',
  off: 1290732,
  size: 298 }
{ name:
   '/pages/editInvitation/component-pages/location/location.html',
  off: 1291030,
  size: 320 }
{ name:
   '/pages/editInvitation/component-pages/reminder/reminder.html',
  off: 1291350,
  size: 569 }
{ name:
   '/pages/editInvitation/component-pages/template/template.html',
  off: 1291919,
  size: 320 }
{ name: '/pages/editInvitation/editInvitation.html',
  off: 1292239,
  size: 339 }
{ name: '/pages/index/component-pages/feedback/feedback.html',
  off: 1292578,
  size: 349 }
{ name: '/pages/index/component-pages/setReminder/setReminder.html',
  off: 1292927,
  size: 396 }
{ name: '/pages/index/index.html', off: 1293323, size: 2188 }
{ name:
   '/pages/invDetail/component-pages/paticipants/paticipants.html',
  off: 1295511,
  size: 503 }
{ name:
   '/pages/invDetail/component-pages/publishFeed/publishFeed.html',
  off: 1296014,
  size: 360 }
{ name: '/pages/invDetail/invDetail.html',
  off: 1296374,
  size: 1335 }
{ name: '/pages/template.html', off: 1297709, size: 263 }
{ name: '/page-frame.html', off: 1297972, size: 95277 }
Saving files...
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...
Splitting "C:\Users\Biao\Desktop\小程序包\wxappUnpacker-master\_1360141122_9\app-service.js" done.

C:\Users\Biao\Desktop\小程序包\wxappUnpacker-master\node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
vm.js:32
return new x;
^^^^^^

SyntaxError: Illegal return statement
    at new Script (vm.js:79:7)
    at VMScript.compile (C:\Users\Biao\Desktop\小程序包\wxappUnpacker-master\node_modules\vm2\lib\main.js:78:20)
    at VM.run (C:\Users\Biao\Desktop\小程序包\wxappUnpacker-master\node_modules\vm2\lib\main.js:204:52)
    at z (C:\Users\Biao\Desktop\小程序包\wxappUnpacker-master\wuWxml.js:366:7)
    at z (C:\Users\Biao\Desktop\小程序包\wxappUnpacker-master\wuRestoreZ.js:244:17)
    at catchZ (C:\Users\Biao\Desktop\小程序包\wxappUnpacker-master\wuRestoreZ.js:28:2)
    at getZ (C:\Users\Biao\Desktop\小程序包\wxappUnpacker-master\wuRestoreZ.js:244:2)
    at wu.get.code (C:\Users\Biao\Desktop\小程序包\wxappUnpacker-master\wuWxml.js:354:3)
    at ioLimit.runWithCb (C:\Users\Biao\Desktop\小程序包\wxappUnpacker-master\wuLib.js:80:8)
    at agent (C:\Users\Biao\Desktop\小程序包\wxappUnpacker-master\wuLib.js:54:14)
PS C:\Users\Biao\Desktop\小程序包\wxappUnpacker-master> node wuWxapkg.js _1360141122_9.wxapkg
Unpack file _1360141122_9.wxapkg...

包在这里：
[_1360141122_9.zip](https://github.com/qwerty472123/wxappUnpacker/files/2591530/_1360141122_9.zip)

**Comment by jdevsean** [comment]
版本：/*v0.6vv_20170214_fbi*/

**Comment by qwerty472123** [comment]
你所给出的版本号本项目并不考虑支持
