### ISSUE TITLE
大牛帮忙看下这个包，是不是 app-service.js被混淆代码干扰，无法解包configs wxss wxml wxs

### ISSUE THREAD

**Issue by zho0ozh** [qwerty472123/wxappUnpacker#182]
链接:https://pan.baidu.com/s/192tfrxvJQWMGFYEwMVx16w 密码:3u17

**Comment by qwerty472123** [comment]
并不是 只是单纯的有插件而已

**Comment by zho0ozh** [comment]
大牛,插件怎么处理

**Comment by qwerty472123** [comment]
手工把插件部分删除

**Comment by qwerty472123** [comment]
node wuWxss.js 后的参数是app-wxss.js所在文件夹 @zho0ozh 
至于自动的插件功能最近我没什么时间 寒假可能会填坑
