### ISSUE TITLE
这个还能用吗？

### ISSUE THREAD

**Issue by feishu** [qwerty472123/wxappUnpacker#199]
我现在找不到 MicroMsg/{User}/appbrand/pkg 目录，是不是小程序新版已经不放在这个目录下了呀

**Comment by Jachin574** [comment]
一直都是这个目录

**Comment by showching** [comment]
> 我现在找不到 MicroMsg/{User}/appbrand/pkg 目录，是不是小程序新版已经不放在这个目录下了呀

你root了吗

**Comment by qwerty472123** [comment]
获取wxapkg不是本项目讨论范围
