### ISSUE TITLE
反编译出错 __mainPageFrameReady__ is not defined

### ISSUE THREAD

**Issue by Rayure** [qwerty472123/wxappUnpacker#200]
node wuWxapkg.js D:\workspace\wxappUnpacker\data\_-542907808_9.wxapkg

Guess wxss(first turn)...

D:\workspace\wxappUnpacker\node_modules\_vm2@3.6.4@vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
ReferenceError: __mainPageFrameReady__ is not defined
    at vm.js:17:5
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at VM.run (D:\workspace\wxappUnpacker\node_modules\_vm2@3.6.4@vm2\lib\main.js:204:72)
    at runVM (D:\workspace\wxappUnpacker\wuWxss.js:69:6)
    at runOnce (D:\workspace\wxappUnpacker\wuWxss.js:86:27)
    at Array.preRun (D:\workspace\wxappUnpacker\wuWxss.js:166:5)
    at CntEvent.decount (D:\workspace\wxappUnpacker\wuLib.js:17:43)
    at ioLimit.runWithCb.err (D:\workspace\wxappUnpacker\wuLib.js:73:11)
    at agent (D:\workspace\wxappUnpacker\wuLib.js:54:14)
    at FSReqWrap.oncomplete (fs.js:135:15)

[_-542907808_9.zip](https://github.com/qwerty472123/wxappUnpacker/files/2790157/_-542907808_9.zip)

**Comment by xjd1123** [comment]
http://thyrsi.com/t6/662/1548336983x1822611383.jpg

帮你解了把jpg改成zip格式解压即可！

**Comment by Rayure** [comment]
> http://thyrsi.com/t6/662/1548336983x1822611383.jpg
> 
> 帮你解了把jpg改成zip格式解压即可！

感谢！

**Comment by fisherli** [comment]
> http://thyrsi.com/t6/662/1548336983x1822611383.jpg
> 
> 帮你解了把jpg改成zip格式解压即可！

你好,你是怎么解决这个问题的? 能教下我吗? 有偿服务

**Comment by xjd1123** [comment]
不提供教程的，也不会写，哈这个是手动处理部分的。

**Comment by tianbymy** [comment]
能不能说下思路？

**Comment by showching** [comment]
正确的姿势：把wuWxss.js第161行修改成：
`
			let mainCode=oriCode.slice(oriCode.indexOf("setCssToHead"),oriCode.lastIndexOf(";__mainPageFrameReady__()"));
`
然后重新run代码。

感谢作者！

**Comment by anda88** [comment]
> 正确的姿势：把wuWxss.js第161行修改成：
> `let mainCode=oriCode.slice(oriCode.indexOf("setCssToHead"),oriCode.lastIndexOf(";__mainPageFrameReady__()"));`
> 然后重新run代码。
> 
> 感谢作者！

照你这个改了，还是报这个错呀

**Comment by showching** [comment]
> > 正确的姿势：把wuWxss.js第161行修改成：
> > `let mainCode=oriCode.slice(oriCode.indexOf("setCssToHead"),oriCode.lastIndexOf(";__mainPageFrameReady__()"));`
> > 然后重新run代码。
> > 感谢作者！
> 
> 照你这个改了，还是报这个错呀

之前生成的文件删掉没有？

**Comment by SUGUANHUI** [comment]
@showching @xjd1123 你好，能帮我看看这个报错吗
![image](https://user-images.githubusercontent.com/44761539/55140908-21678780-5174-11e9-91fc-951269fc839a.png)
