### ISSUE TITLE
提示成功，但是所有js文件都是undefined

### ISSUE THREAD

**Issue by kakaxi114** [qwerty472123/wxappUnpacker#22]
node wuJs.js app-service.js
Splitting "app-service.js" done.
Total use: 132.945ms

但是所有js文件都是undefined

app-service.js文件开头代码

var __wxAppData = {}; 	var __wxRoute; 	var __wxRouteBegin; 	var __wxAppCode__ = {};	var global = {};	var __wxAppCurrentFile__; 	var Component = Component || function(){};	var definePlugin = definePlugin || function(){};	var requirePlugin = requirePlugin || function(){};	var Behavior = Behavior || function(){};
	
	define("launchModules/launcher.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
(function(){'use strict';function a(a){return function(){var c=a.apply(this,arguments);return new b.Promise(function(a,d){function e(f,g){try{var h=c[f](g),i=h.value}catch(a){return void d(a)}return h.done?void a(i):b.Promise.resolve(i).then(function(a){e('next',a)},function(a){e('throw',a)})}return e('next')})}}require('../utils/polyfill');var b=require('../utils/promise-polyfill'),c=require('../lib/runtime'),d=function(a){return a&&a.__esModule?a:{default:a}}(c),e=require('../utils/login'),f=require('../utils/const');module.exports={appName:f.appName,privateDeployMent:f.privateDeployMent,launcher:function(b){var c=this;return a(d.default.mark(function a(){return d.default.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return c.globalData.appName=f.appName,a.abrupt('return',(0,e.wxLogin)().then(function(a){'error'===a||c.globalData.userInfo.sessid||(0,e.wxAuth)(a,f.appName).then(function(d){if(console.log(d.ret),'logined'===d.ret.act)c.globalData.userInfo=d.ret.userInfo,c.globalData.userInfo.code=a,c.userInfoReadyCallback&&c.userInfoReadyCallback(d.ret.userInfo);else{c.globalData.userInfo.code=a,c.globalData.userInfo.sessid=d.ret.sessid,c.globalData.userInfo.openId=d.ret.openId;var e=f.privateDeployMent?'../login/login':'../initPage/initPage';wx.redirectTo({url:e})}b,setData({dataReady:!0,error:!1})},function(){b.setData({dataReady:!1,error:!0})})}));case 2:case'end':return a.stop();}},a,c)}))()}}})(); 
 			}); 
		define("lib/runtime.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){

**Comment by kakaxi114** [comment]
程序内容

**Comment by kakaxi114** [comment]
程序代码下载：链接: https://pan.baidu.com/s/1VOsGBqSdqYi0bbhxUv3k6Q 密码: xpsw

**Comment by qwerty472123** [comment]
js部分稍微强化了一波
