### ISSUE TITLE
免费解包，传承作者开源精神，QQ9349540,来者不拒

### ISSUE THREAD

**Issue by qq9349540** [qwerty472123/wxappUnpacker#221]
###比较痛恨拿人免费开源的作品收费的人###
就这样，还有我做了个在线站点，介于涉嫌宣传就不发了，行内人应该多多少少知道（PS：端口3000）
然后认识我的请顶贴吧

**Comment by LukeDev2K** [comment]
不认识啊

**Comment by jacksuc** [comment]
不认识+1

**Comment by futurecxp** [comment]
> ###比较痛恨拿人免费开源的作品收费的人### 
> 就这样，还有我做了个在线站点，介于涉嫌宣传就不发了，行内人应该多多少少知道（PS：端口3000 ）
> 然后认识我的请顶贴吧
你那QQ加不上的  世间无道  技无顶峰 学海无涯 
的答案呢....

**Comment by tianbymy** [comment]
分包能解么？

**Comment by 7423385** [comment]
联系QQ 7423385

**Comment by gudqs7** [comment]
> 分包能解么？
@tianbymy  能
https://github.com/gudqs7/wxappUnpacker

**Comment by 15192095633** [comment]
在线站点是什么啊？
