### ISSUE TITLE
小程序云开发项目能被反编译吗？

### ISSUE THREAD

**Issue by BunnyShing** [qwerty472123/wxappUnpacker#222]
微信小程序的云开发项目能被反编译吗？
1、如果能被反编译，那么岂不是会被任意操纵原项目的云数据库？因为project.config.json中就有原作者的appid。
2、云函数能被反编译出来吗？

**Comment by 7423385** [comment]
可以

**Comment by liangqiubing** [comment]
云函数运行在服务器云端，你能够入侵腾讯服务器话，应该能搞定。

**Comment by BunnyShing** [comment]
> 云函数运行在服务器云端，你能够入侵腾讯服务器话，应该能搞定。

问题是，云开发项目中小程序端也能通过API操作云端数据库，这个就大问题了

**Comment by liangqiubing** [comment]
小程序端操作云端数据库，也需要登录和权限，如果你能跳过这个步骤，相当于入侵腾讯服务器了。

**Comment by BunnyShing** [comment]
> 小程序端操作云端数据库，也需要登录和权限，如果你能跳过这个步骤，相当于入侵腾讯服务器了。

十分感谢你的指引，我刚刚仔细重新看了云开发关于数据库的部分，云开发的数据库的确有严格权限限制，用户的确无法随意修改数据库中的数据
