### ISSUE TITLE
/ v0.6vv_20180125_fbi /内新增的_af请问怎么处理呢？

### ISSUE THREAD

**Issue by IMYalo** [qwerty472123/wxappUnpacker#23]
> ## /*v0.6vv_20180125_fbi*/ 内新增的：

`function _af(p, a, c){`
`p.extraAttr = {"t_action": a, "t_cid": c};`
`}`

> 代码片段：
`
var m0=function(e,s,r,gg){
var oB=_v()
_(r,oB)
if(_o(0,e,s,gg)){oB.wxVkey=1
var oD=_n('loading')
var fE=_o(1,e,s,gg)
_(oD,fE)
_(oB,oD)
}
var xC=_v()
_(r,xC)
if(_o(2,e,s,gg)){xC.wxVkey=1
var cF=_n('view')
_r(cF,'class',3,e,s,gg)
var oH=_n('view')
_r(oH,'class',4,e,s,gg)
var cI=_m('view',['class',5,'style',1],[],e,s,gg)
var oJ=_m('view',['class',7,'style',1],[],e,s,gg)
var lK=_o(9,e,s,gg)
_(oJ,lK)
_(cI,oJ)
_(oH,cI)
var aL=_m('view',['class',10,'style',1],[],e,s,gg)
var tM=_n('view')
_r(tM,'class',12,e,s,gg)
var eN=_o(13,e,s,gg)
_(tM,eN)
_(aL,tM)
var bO=_n('view')
_r(bO,'class',14,e,s,gg)
var oP=_o(15,e,s,gg)
_(bO,oP)
_(aL,bO)
_(oH,aL)
_(cF,oH)
var xQ=_n('view')
_r(xQ,'class',16,e,s,gg)
var hU=_n('view')
_r(hU,'class',17,e,s,gg)
var oV=_n('view')
_r(oV,'class',18,e,s,gg)
var cW=_o(19,e,s,gg)
_(oV,cW)
_(hU,oV)
_(xQ,hU)
var oX=_v()
_(xQ,oX)
var lY=function(t1,aZ,e2,gg){
var o4=_n('radio-group')
var x5=_v()
_(o4,x5)
if(_o(21,t1,aZ,gg)){x5.wxVkey=1
var o0=_m('label',['bindtap',22,'data-name',1],[],t1,aZ,gg)
_af(o0,1,463);
var cAB=_n('view')
_r(cAB,'class',24,t1,aZ,gg)
var oBB=_n('view')
_r(oBB,'class',25,t1,aZ,gg)
var lCB=_m('image',['alt',26,'src',1],[],t1,aZ,gg)
_(oBB,lCB)
_(cAB,oBB)
var aDB=_n('view')
_r(aDB,'class',28,t1,aZ,gg)
var tEB=_o(29,t1,aZ,gg)
_(aDB,tEB)
_(cAB,aDB)
var eFB=_n('view')
_r(eFB,'class',30,t1,aZ,gg)
var bGB=_m('radio',['checked',31,'class',1,'color',2,'data-type',3,'id',4,'value',5],[],t1,aZ,gg)
_(eFB,bGB)
_(cAB,eFB)
_(o0,cAB)
_(x5,o0)
}
var o6=_v()
_(o4,o6)
if(_o(37,t1,aZ,gg)){o6.wxVkey=1
var oHB=_m('label',['bindtap',38,'data-name',1],[],t1,aZ,gg)
_af(oHB,1,464);
var xIB=_n('view')
_r(xIB,'class',40,t1,aZ,gg)
var oJB=_n('view')
_r(oJB,'class',41,t1,aZ,gg)
var fKB=_m('image',['alt',42,'src',1],[],t1,aZ,gg)
_(oJB,fKB)
_(xIB,oJB)
var cLB=_n('view')
_r(cLB,'class',44,t1,aZ,gg)
var hMB=_o(45,t1,aZ,gg)
_(cLB,hMB)
_(xIB,cLB)
var oNB=_n('view')
_r(oNB,'class',46,t1,aZ,gg)
var cOB=_m('radio',['checked',47,'class',1,'color',2,'data-type',3,'value',4],[],t1,aZ,gg)
_(oNB,cOB)
_(xIB,oNB)
_(oHB,xIB)
_(o6,oHB)
}
var f7=_v()
_(o4,f7)
if(_o(52,t1,aZ,gg)){f7.wxVkey=1
var oPB=_m('label',['bindtap',53,'data-name',1],[],t1,aZ,gg)
_af(oPB,1,465);
var lQB=_n('view')
_r(lQB,'class',55,t1,aZ,gg)
var aRB=_n('view')
_r(aRB,'class',56,t1,aZ,gg)
var tSB=_m('image',['alt',57,'src',1],[],t1,aZ,gg)
_(aRB,tSB)
_(lQB,aRB)
var eTB=_n('view')
_r(eTB,'class',59,t1,aZ,gg)
var bUB=_o(60,t1,aZ,gg)
_(eTB,bUB)
_(lQB,eTB)
var oVB=_n('view')
_r(oVB,'class',61,t1,aZ,gg)
var xWB=_m('radio',['checked',62,'class',1,'color',2,'data-type',3,'value',4],[],t1,aZ,gg)
_(oVB,xWB)
_(lQB,oVB)
_(oPB,lQB)
_(f7,oPB)
}
var c8=_v()
_(o4,c8)
if(_o(67,t1,aZ,gg)){c8.wxVkey=1
var oXB=_n('view')
_r(oXB,'class',68,t1,aZ,gg)
var fYB=_n('view')
_r(fYB,'class',69,t1,aZ,gg)
var cZB=_o(70,t1,aZ,gg)
_(fYB,cZB)
_(oXB,fYB)
var h1B=_n('view')
_r(h1B,'class',71,t1,aZ,gg)
var o2B=_m('input',['bindinput',72,'class',1,'data-type',2,'max',3,'placeholder',4,'type',5,'value',6],[],t1,aZ,gg)
_(h1B,o2B)
_(oXB,h1B)
_(c8,oXB)
var c3B=_n('view')
_r(c3B,'class',79,t1,aZ,gg)
var o4B=_n('view')
_r(o4B,'class',80,t1,aZ,gg)
var l5B=_o(81,t1,aZ,gg)
_(o4B,l5B)
_(c3B,o4B)
var a6B=_n('view')
_r(a6B,'class',82,t1,aZ,gg)
var t7B=_m('input',['bindinput',83,'class',1,'data-type',2,'max',3,'placeholder',4,'value',5],[],t1,aZ,gg)
_(a6B,t7B)
_(c3B,a6B)
_(c8,c3B)
var e8B=_n('view')
_r(e8B,'class',89,t1,aZ,gg)
var b9B=_n('view')
_r(b9B,'class',90,t1,aZ,gg)
var o0B=_o(91,t1,aZ,gg)
_(b9B,o0B)
_(e8B,b9B)
var xAC=_n('view')
_r(xAC,'class',92,t1,aZ,gg)
var oBC=_m('input',['bindinput',93,'class',1,'data-type',2,'max',3,'placeholder',4,'value',5],[],t1,aZ,gg)
_(xAC,oBC)
_(e8B,xAC)
_(c8,e8B)
}
var h9=_v()
_(o4,h9)
if(_o(99,t1,aZ,gg)){h9.wxVkey=1
var fCC=_m('label',['bindtap',100,'data-name',1],[],t1,aZ,gg)
_af(fCC,1,466);
var cDC=_n('view')
_r(cDC,'class',102,t1,aZ,gg)
var hEC=_n('view')
_r(hEC,'class',103,t1,aZ,gg)
var oFC=_m('image',['alt',104,'src',1],[],t1,aZ,gg)
_(hEC,oFC)
_(cDC,hEC)
var cGC=_n('view')
_r(cGC,'class',106,t1,aZ,gg)
var oHC=_o(107,t1,aZ,gg)
_(cGC,oHC)
_(cDC,cGC)
var lIC=_n('view')
_r(lIC,'class',108,t1,aZ,gg)
var aJC=_m('radio',['checked',109,'class',1,'color',2,'data-type',3,'value',4],[],t1,aZ,gg)
_(lIC,aJC)
_(cDC,lIC)
_(fCC,cDC)
_(h9,fCC)
}
x5.wxXCkey=1
o6.wxXCkey=1
f7.wxXCkey=1
c8.wxXCkey=1
h9.wxXCkey=1
_(e2,o4)
return e2
}
oX.wxXCkey=2
_2(20,lY,e,s,gg,oX,'item','index','')
var oR=_v()
_(xQ,oR)
if(_o(114,e,s,gg)){oR.wxVkey=1
var tKC=_n('view')
_r(tKC,'class',115,e,s,gg)
var eLC=_n('view')
_r(eLC,'class',116,e,s,gg)
var bMC=_o(117,e,s,gg)
_(eLC,bMC)
_(tKC,eLC)
var oNC=_n('view')
_r(oNC,'class',118,e,s,gg)
var xOC=_m('input',['bindinput',119,'class',1,'data-type',2,'max',3,'placeholder',4,'type',5,'value',6],[],e,s,gg)
_(oNC,xOC)
_(tKC,oNC)
_(oR,tKC)
}
var fS=_v()
_(xQ,fS)
if(_o(126,e,s,gg)){fS.wxVkey=1
var oPC=_n('view')
_r(oPC,'class',127,e,s,gg)
var fQC=_n('view')
_r(fQC,'class',128,e,s,gg)
var cRC=_n('span')
_r(cRC,'class',129,e,s,gg)
var hSC=_o(130,e,s,gg)
_(cRC,hSC)
_(fQC,cRC)
_(oPC,fQC)
var oTC=_m('picker',['bindchange',131,'class',1,'range',2,'rangeKey',3,'value',4],[],e,s,gg)
var cUC=_o(136,e,s,gg)
_(oTC,cUC)
_(oPC,oTC)
var oVC=_n('view')
_r(oVC,'class',137,e,s,gg)
_(oPC,oVC)
_(fS,oPC)
}
var cT=_v()
_(xQ,cT)
if(_o(138,e,s,gg)){cT.wxVkey=1
var lWC=_n('view')
_r(lWC,'class',139,e,s,gg)
var aXC=_n('view')
_r(aXC,'class',140,e,s,gg)
var tYC=_o(141,e,s,gg)
_(aXC,tYC)
_(lWC,aXC)
var eZC=_n('view')
_r(eZC,'class',142,e,s,gg)
var b1C=_m('input',['bindinput',143,'class',1,'data-type',2,'max',3,'placeholder',4,'value',5],[],e,s,gg)
_(eZC,b1C)
_(lWC,eZC)
_(cT,lWC)
var o2C=_n('view')
_r(o2C,'class',149,e,s,gg)
var x3C=_n('view')
_r(x3C,'class',150,e,s,gg)
var o4C=_o(151,e,s,gg)
_(x3C,o4C)
_(o2C,x3C)
var f5C=_n('view')
_r(f5C,'class',152,e,s,gg)
var c6C=_m('input',['bindinput',153,'class',1,'data-type',2,'max',3,'placeholder',4,'value',5],[],e,s,gg)
_(f5C,c6C)
_(o2C,f5C)
_(cT,o2C)
}
oR.wxXCkey=1
fS.wxXCkey=1
cT.wxXCkey=1
_(cF,xQ)
var hG=_v()
_(cF,hG)
if(_o(159,e,s,gg)){hG.wxVkey=1
var h7C=_n('view')
_r(h7C,'class',160,e,s,gg)
var o0C=_n('view')
_r(o0C,'class',161,e,s,gg)
var lAD=_n('view')
_r(lAD,'class',162,e,s,gg)
var aBD=_o(163,e,s,gg)
_(lAD,aBD)
_(o0C,lAD)
_(h7C,o0C)
var o8C=_v()
_(h7C,o8C)
if(_o(164,e,s,gg)){o8C.wxVkey=1
var tCD=_n('view')
_r(tCD,'class',165,e,s,gg)
var eDD=_n('view')
_r(eDD,'class',166,e,s,gg)
var bED=_o(167,e,s,gg)
_(eDD,bED)
_(tCD,eDD)
_(o8C,tCD)
}
var c9C=_v()
_(h7C,c9C)
if(_o(168,e,s,gg)){c9C.wxVkey=1
var oFD=_n('view')
_r(oFD,'class',169,e,s,gg)
var xGD=_n('view')
_r(xGD,'class',170,e,s,gg)
var oHD=_o(171,e,s,gg)
_(xGD,oHD)
_(oFD,xGD)
_(c9C,oFD)
}
var fID=_n('view')
_r(fID,'class',172,e,s,gg)
var cJD=_n('view')
_r(cJD,'class',173,e,s,gg)
var hKD=_o(174,e,s,gg)
_(cJD,hKD)
_(fID,cJD)
_(h7C,fID)
o8C.wxXCkey=1
c9C.wxXCkey=1
_(hG,h7C)
}
var oLD=_m('view',['bindtap',175,'class',1],[],e,s,gg)
_af(oLD,1,467);
var cMD=_o(177,e,s,gg)
_(oLD,cMD)
_(cF,oLD)
var oND=_n('view')
_r(oND,'class',178,e,s,gg)
var lOD=_n('view')
_r(lOD,'class',179,e,s,gg)
var aPD=_o(180,e,s,gg)
_(lOD,aPD)
_(oND,lOD)
_(cF,oND)
hG.wxXCkey=1
_(xC,cF)
}
oB.wxXCkey=1
xC.wxXCkey=1
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
d_[x[1]]={}
`

> 请问如何处理呢？

**Comment by qwerty472123** [comment]
你这样一个代码片段没有前后逻辑，我怎么知道呢？

**Comment by IMYalo** [comment]
[page-frame.zip](https://github.com/qwerty472123/wxappUnpacker/files/1865848/page-frame.zip)
完整的html在里面

**Comment by qwerty472123** [comment]
看不出来有af什么用，先忽略处理吧（主要是找不到能生成对应版本代码的wcc.exe,也没有对应的运行时环境，看不出来extraAttr有什么用 ）
