### ISSUE TITLE
__vd_version_info__ is not defined

### ISSUE THREAD

**Issue by SLiGe** [qwerty472123/wxappUnpacker#237]
各位大神，这个问题遇到过吗，处理分包时候的
throw this._internal.Decontextify.value(e);
                        ^
ReferenceError: __vd_version_info__ is not defined
    at vm.js:3:3
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at VM.run (C:\Users\Administrator\Desktop\node1\node_modules\vm2\lib\main.js:204:72)
    at runVM (C:\Users\Administrator\Desktop\node1\wuWxss.js:97:4)
    at runOnce (C:\Users\Administrator\Desktop\node1\wuWxss.js:121:27)
    at Array.preRun (C:\Users\Administrator\Desktop\node1\wuWxss.js:201:5)
    at CntEvent.decount (C:\Users\Administrator\Desktop\node1\wuLib.js:17:43)
    at ioLimit.runWithCb (C:\Users\Administrator\Desktop\node1\wuLib.js:81:11)
    at agent (C:\Users\Administrator\Desktop\node1\wuLib.js:54:14)
    at tryToString (fs.js:513:3)

**Comment by caominkeji** [comment]
同求

**Comment by caominkeji** [comment]
@qwerty472123 大佬，大佬快快出山吧

**Comment by zjjzff1** [comment]
这个项目已经没有人维护了，据说大佬被tx警告了

**Comment by iskyc** [comment]
wuWxss.jss找到这个函数，替换成这个代码试试
```

function runOnce() {
		for (let name in runList) {
			// console.log(name, runList[name]);
			var start = `var window = window || {}; var __pageFrameStartTime__ = Date.now(); 	var __webviewId__; 	var __wxAppCode__={}; 	var __mainPageFrameReady__ = function(){}; 	var __WXML_GLOBAL__={entrys:{},defines:{},modules:{},ops:[],wxs_nf_init:undefined,total_ops:0}; 	var __vd_version_info__=__vd_version_info__||{};	 
			
			$gwx=function(path,global){
				if(typeof global === 'undefined') global={};if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
				}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
			}`;
			runVM(name, start + " \r\n" + runList[name]);
		}
	}
```

**Comment by caominkeji** [comment]
@iskyc 可以了但是分包的wxss也不出来了，提示这个了 C:\Users\Administrator\Desktop\node1\node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
ReferenceError: $gwx0 is not defined
    at vm.js:10:8
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at VM.run (C:\Users\Administrator\Desktop\node1\node_modules\vm2\lib\main.js:204:72)
    at runVM (C:\Users\Administrator\Desktop\node1\wuWxss.js:89:4)
    at runOnce (C:\Users\Administrator\Desktop\node1\wuWxss.js:121:4)
    at Array.preRun (C:\Users\Administrator\Desktop\node1\wuWxss.js:202:5)
    at CntEvent.decount (C:\Users\Administrator\Desktop\node1\wuLib.js:17:43)
    at ioLimit.runWithCb (C:\Users\Administrator\Desktop\node1\wuLib.js:81:11)
    at agent (C:\Users\Administrator\Desktop\node1\wuLib.js:54:14)
    at tryToString (fs.js:513:3)

**Comment by caominkeji** [comment]
@iskyc 搞定了

**Comment by skybird** [comment]
@caominkeji 请问怎么搞定的？

我目前就找到一个蠢办法，直接找到判断__vd_version_info__的代码
if (__vd_version_info__.delayedGwx) __wxAppCode__['pages/user/user.wxml'] = [ $gwx, './pages/user/user.wxml' ];
else __wxAppCode__['pages/user/user.wxml'] = $gwx( './pages/user/user.wxml' );

改成
__wxAppCode__['pages/user/user.wxml'] = $gwx( './pages/user/user.wxml' );

ps：如果页面多，删起来很繁琐

**Comment by skybird** [comment]
之前的代码存在问题，重新申明的变量太多，会覆盖原有的变量，导致无法解析出wxss，如下方式比较简单！
`
function runOnce() {
		for (let name in runList) {
			var start = `var __vd_version_info__=__vd_version_info__||{};`;
			runVM(name, start + runList[name]);
		}
	}
`

**Comment by Amazingzl** [comment]
> wuWxss.jss找到这个函数，替换成这个代码试试
> 
> ```
> 
> function runOnce() {
> 		for (let name in runList) {
> 			// console.log(name, runList[name]);
> 			var start = `var window = window || {}; var __pageFrameStartTime__ = Date.now(); 	var __webviewId__; 	var __wxAppCode__={}; 	var __mainPageFrameReady__ = function(){}; 	var __WXML_GLOBAL__={entrys:{},defines:{},modules:{},ops:[],wxs_nf_init:undefined,total_ops:0}; 	var __vd_version_info__=__vd_version_info__||{};	 
> 			
> 			$gwx=function(path,global){
> 				if(typeof global === 'undefined') global={};if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
> 				}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
> 			}`;
> 			runVM(name, start + " \r\n" + runList[name]);
> 		}
> 	}
> ```

666

**Comment by wec246810** [comment]
不行啊，换了之后，所有的wxss文件都没了

**Comment by x888666y** [comment]
完美解决ReferenceError: vd_version_info is not defined问题，请看：https://www.jianshu.com/p/357d34c5917e

**Comment by wec246810** [comment]
滚你妈逼的广告，想钱想疯了吧



------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>; 
发送时间: 2019年6月10日(星期一) 下午5:10
收件人: "qwerty472123/wxappUnpacker"<wxappUnpacker@noreply.github.com>; 
抄送: "Mr.Yang"<1176971130@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [qwerty472123/wxappUnpacker] __vd_version_info__ is not defined(#237)




完美解决$gwx is not defined和ReferenceError: vd_version_info is not defined问题，请看：https://www.jianshu.com/p/357d34c5917e
 
&mdash;

**Comment by IMYalo** [comment]
就是啊！！大伙儿一起上，狂草它那八十岁的老麻麻~




------------------ 原始邮件 ------------------
发件人: "wec246810"<notifications@github.com>; 
发送时间: 2019年6月10日(星期一) 下午5:13
收件人: "qwerty472123/wxappUnpacker"<wxappUnpacker@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [qwerty472123/wxappUnpacker] __vd_version_info__ is not defined(#237)



滚你妈逼的广告，想钱想疯了吧 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "notifications"<notifications@github.com>;  
 发送时间: 2019年6月10日(星期一) 下午5:10 
 收件人: "qwerty472123/wxappUnpacker"<wxappUnpacker@noreply.github.com>;  
 抄送: "Mr.Yang"<1176971130@qq.com>; "Comment"<comment@noreply.github.com>;  
 主题: Re: [qwerty472123/wxappUnpacker] __vd_version_info__ is not defined(#237) 
 
 
 
 
 完美解决$gwx is not defined和ReferenceError: vd_version_info is not defined问题，请看：https://www.jianshu.com/p/357d34c5917e 
   
 &mdash;

**Comment by jqClub** [comment]
> 不行啊，换了之后，所有的wxss文件都没了

我用的这个库，可以编译成功https://github.com/gudqs7/wxappUnpacker

**Comment by turbochoo** [comment]
> > 不行啊，换了之后，所有的wxss文件都没了
> 
> 我用的这个库，可以编译成功https://github.com/gudqs7/wxappUnpacker

部分能ok ,有得就不行，page页面都是空的，例如我看一个wxml, 里面只有  <text>pages/main/login.wxml</text>
