### ISSUE TITLE
 v0.6vv_20171120_cua_xc版本的问题

### ISSUE THREAD

**Issue by luckyhong** [qwerty472123/wxappUnpacker#24]
你好，我在使用作者提供的 工具 运行过程中好像也遇到版本适配问题， 想咨询下作者目前
 v0.6vv_20171120_cua_xc版本的问题 适配好了吗？ 还望得到作者的回复

**Comment by qwerty472123** [comment]
没有，不想`适配`了, 本来就是一个分享一个相关的思路的小工具而不是生产环境的实用工具，原则上不想搞面向低版本的适配（使用本软件不应以`破解`特定微信小程序为目的。）

**Comment by luckyhong** [comment]
11个小时前我有收到你对我提的这条issue的回复，可能你误会我使用这个反编译的初衷目的，我也是秉着学习的目的来研究反编译，并没有想过用于不法目的，可能自身能力不够无法适配不同版本，你发的这个实现细节https://github.com/qwerty472123/wxappUnpacker/blob/master/DETAILS.md 我也有研究过，但是就是不知在哪里适配，所以才想咨询下作者，没想到却让你误会，真是抱歉了。

**Comment by qwerty472123** [comment]
@luckyhong 一开始心情不太好~ 另外其实也很无奈，手头有的正向编译工具就微信开发者工具最新的那个版本，没有正向编译工具的话适配很多只能靠猜，你这样空手不给包（现在也不用给，我已经决定不干旧版本适配了）的当然更加让我无能为力了。
哪里适配的话比如几乎所有操作都是先从包中的代码中通过字符串匹配截取一部分, 不同版本由于函数的删改等原因，这部分需要先用肉眼定位，然后选择合适的字符串截取方案。
剩下的也就wxml上可能增/改几个函数，这些函数在我匹配的版本中的功能在<https://github.com/qwerty472123/wxappUnpacker/blob/master/DETAILS.md>描述的很详细，变动也完全可以通过阅读platform-page.html来获知。
如果你适配过程中遇到**具体**的问题，也欢迎来咨询。
