### ISSUE TITLE
运行工具，控制台报错

### ISSUE THREAD

**Issue by zhang80688** [qwerty472123/wxappUnpacker#25]
你好， 程序报错如下，
![image](https://user-images.githubusercontent.com/17794912/38309896-c054fb34-384d-11e8-9c42-b0efe0fd8c56.png)
麻烦你帮我解决下这个问题， wxapkg文件包在附件：
[_1074959078_4.zip](https://github.com/qwerty472123/wxappUnpacker/files/1875874/_1074959078_4.zip)

**Comment by qwerty472123** [comment]
这不是报错啊，见`局限`中的最后一条，编译是个信息丢失的过程，丢失的信息不可能被还原。
很多其他的还原工具甚至不处理import关系直接把wxss的import语句改成import内容本身的，那会使得结构更加不清晰。
