### ISSUE TITLE
大佬，这个包解不了，有人帮忙解包吗

### ISSUE THREAD

**Issue by dengbaoling** [qwerty472123/wxappUnpacker#251]
发表 Issue 前请仔细阅读以下内容：

模板内容如下：

程序执行命令(可选):

程序执行错误信息(如果反馈是抛出异常的错误，必填):
![image](https://user-images.githubusercontent.com/17171011/57712686-9bf85200-76a3-11e9-9a3f-19302a164f83.png)

[514.txt](https://github.com/qwerty472123/wxappUnpacker/files/3178726/514.txt)
包文件是514.txt下载改成wxapkg即可
```
复制到这里
```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):

其他附加内容:

**Comment by dengbaoling** [comment]
[
[514.txt](https://github.com/qwerty472123/wxappUnpacker/files/3178726/514.txt)

](url)

**Comment by dengbaoling** [comment]
大佬们抓包都用哪个模拟器，最近发现模拟器打开小程序都闪退

**Comment by 15192095633** [comment]
245880392 免费给你解。
