### ISSUE TITLE
解子包 出现如下报错

### ISSUE THREAD

**Issue by rocky-76** [qwerty472123/wxappUnpacker#253]
![54A5FFAE-1A5A-4421-966C-29F44AA79EB9](https://user-images.githubusercontent.com/9004674/58184961-b3a78a00-7ce4-11e9-8c41-67ea6bc95e99.png)
例如 a 为主包 ，b为子包， 解完主包得到文件夹a 然后解子包输入命令                                                
` node wuWxapkg.js /user/xx/b.wxapkg -s=/user/xx/a `  就会报上面的错误提示

**Comment by rocky-76** [comment]
![54A5FFAE-1A5A-4421-966C-29F44AA79EB9](https://user-images.githubusercontent.com/9004674/58184961-b3a78a00-7ce4-11e9-8c41-67ea6bc95e99.png)
例如 a 为主包 ，b为子包

**Comment by 245880392** [comment]
路径不对吧。

**Comment by qwerty472123** [comment]
本项目暂不支持该功能
