### ISSUE TITLE
无法还原wxml文件

### ISSUE THREAD

**Issue by tfzxyinhao** [qwerty472123/wxappUnpacker#31]
![image](https://user-images.githubusercontent.com/444814/38739603-f2e65a40-3f67-11e8-8b7f-fc7dfcbc3d46.png)

[group_love.zip](https://github.com/qwerty472123/wxappUnpacker/files/1907641/group_love.zip)

**Comment by qwerty472123** [comment]
旧有版本(`v0.6vv_20171208_cua_xc`)不提供兼容性支持
见([局限1](https://github.com/qwerty472123/wxappUnpacker/blob/master/README.md#%E5%B1%80%E9%99%90) #19 #21 #24 #26 #27)

**Comment by tfzxyinhao** [comment]
这个不是zip 是wxapkg 包无法直接解压的,便于上传附件才改成zip

**Comment by qwerty472123** [comment]
@tfzxyinhao 我知道啊 但是wxapkg内的wxml对应的js代码使用旧版本wcc"编译器"生成的，所以不支持。

**Comment by qwerty472123** [comment]
是啊
