### ISSUE TITLE
大佬，能出个小白使用教程就完美了~~~

### ISSUE THREAD

**Issue by zbqiang8** [qwerty472123/wxappUnpacker#33]
大佬，能出个小白使用教程就完美了~~~

**Comment by qwerty472123** [comment]
本项目的目的在于交流一种方法，而不是作为一种实用工具。
这个工具也不可能面向什么都不懂的小白，你要获取源码首先重要看得懂吧, 自己看微信教程(https://developers.weixin.qq.com/miniprogram/dev/)。
然后你只要会nodejs最基本的操作就ok了，这比前面那个简单多了，随便找个nodejs教程不就好了吗。
