### ISSUE TITLE
小程序分包后unpacker不成功

### ISSUE THREAD

**Issue by cjp472** [qwerty472123/wxappUnpacker#34]
使用分包加载后（<https://developers.weixin.qq.com/miniprogram/dev/framework/subpackages.html>），小程序的主包可以解压，但子包解压不了
附件上传一个子包示例
[_1670734126_44.wxapkg.zip](https://github.com/qwerty472123/wxappUnpacker/files/1924440/_1670734126_44.wxapkg.zip)

参考小程序『记帐熊微电商系统』
解压时报错：
wxappUnpacker-extjson/wuWxapkg.js:95
	}else throw Error("This Package is unrecognizable, please decrypted every type of file by hand.")
	      ^

Error: This Package is unrecognizable, please decrypted every type of file by hand.
    at Array.packDone (wxappUnpacker-extjson/wuWxapkg.js:95:14)
    at CntEvent.decount (wxappUnpacker-extjson/wuLib.js:17:43)
    at fs.writeFile.err (wxappUnpacker-extjson/wuLib.js:41:11)
    at FSReqWrap.oncomplete (fs.js:149:20)

**Comment by qwerty472123** [comment]
emm…小程序还有这种操作啊

**Comment by cjp472** [comment]
解开看没有page-frame.html,也没有app-wxss.js, 只有一个app-service.js和一个page-frame.js,其中app-service.js可以用wuJs.js解开，但page-frame.js用wuWxml.js解不开
[两个js.zip](https://github.com/qwerty472123/wxappUnpacker/files/1924750/js.zip)

**Comment by qwerty472123** [comment]
现阶段你可以附上一些手工操作,比如解包后运行
node wuWxml.js package\pack-A\page-frame.js
node wuJs.js package\pack-A\app-service.js
然后手动合并包就ok了

如果有完整的所有包样例提供就更好了
我会考虑支持这部分自动化操作

**Comment by cjp472** [comment]
好的，多谢，关键是page-frame.js解不了，上面那个zip包就是示例

**Comment by qwerty472123** [comment]
@cjp472 增强判断解决了这点
同时希望有完整的所有包样例提供

**Comment by qwerty472123** [comment]
也支持wxss了 同样手动版

**Comment by cjp472** [comment]
多谢，附件是完整的包样例，含有主包和子包
[all.zip](https://github.com/qwerty472123/wxappUnpacker/files/1926117/all.zip)
