### ISSUE TITLE
这个包解析成功，但运行报错，看看什么问题

### ISSUE THREAD

**Issue by zjjzff1** [qwerty472123/wxappUnpacker#37]
这个包解析成功，但运行报错，看看什么问题

[debug_908956821_2_-2104474654.zip](https://github.com/qwerty472123/wxappUnpacker/files/1934173/debug_908956821_2_-2104474654.zip)

**Comment by qwerty472123** [comment]
项目设置里把ES6转ES5关掉因为已经转过了，再转一遍会出bug...
然后大概就是 xjd1123 说的服务器的问题了，本项目不背锅...
感谢你的样例，感谢 @xjd1123 帮助进行分析
