### ISSUE TITLE
node wuWxml.js 报错，提示x未找到

### ISSUE THREAD

**Issue by DCdafan** [qwerty472123/wxappUnpacker#40]
node wxappUnpacker/wuWxml.js _143412895_1.wxapkg_dir/page-frame.html 

/Users/dandan/Desktop/wxx/node_modules/vm2/lib/main.js:218
			throw this._internal.Decontextify.value(e);
			^
ReferenceError: x is not defined

**Comment by qwerty472123** [comment]
你看一下版本 低于2018不支持

**Comment by DCdafan** [comment]
[_143412895_1.wxapkg.zip](https://github.com/qwerty472123/wxappUnpacker/files/1954257/_143412895_1.wxapkg.zip)
@qwerty472123 有空瞅瞅这个噻，感谢大神

**Comment by qwerty472123** [comment]
就是旧版本，旧版本的支持我在较长一段时间内都不可能干的。可以自学修改
其实一般玩个特定小程序也不用彻底(能编译的)反编译啊
