### ISSUE TITLE
node wuWxapkg.js 运行错误

### ISSUE THREAD

**Issue by GanLuo96214** [qwerty472123/wxappUnpacker#42]
(如果你是要反馈 bug, 请按以下格式书写 Issue; 如果你遇到的是 Node.js 使用问题, 请尽可能依赖搜索引擎解决问题; 任何对某类小程序包的适配问题都应提供 wxapkg 程序包，否则直接 Close 处理; 提交前请确认 wxapkg 程序包版本不小于 v0.6vv_20180111_fbi (直接用文本编辑器打开 wxapkg包搜索 v0.6vv 即可查到), 旧版本不提供支持, 相关 Issue 直接 Close 处理。)

程序执行命令(可选):
 node wuWxapkg.js ./pkg 
程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
/Users/gl/Documents/github/wxappUnpacker/wuLib.js:65
		else if(stats.isFile())throw Error(dir+" was created as a file, so we cannot put file into it.");
		                       ^

Error: /Users/gl/Documents/github/wxappUnpacker/pkg was created as a file, so we cannot put file into it.
    at ioLimit.runWithCb (/Users/gl/Documents/github/wxappUnpacker/wuLib.js:65:32)
    at agent (/Users/gl/Documents/github/wxappUnpacker/wuLib.js:54:14)
    at FSReqWrap.oncomplete (fs.js:150:5)
```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):
能邮件给你吗？
其他附加内容:

**Comment by qwerty472123** [comment]
请将pkg文件重命名为aa.wxapkg后再试
如还不行发一份过来(####为@)
4qwerty7####163.com

**Comment by GanLuo96214** [comment]
解决了
