### ISSUE TITLE
含开放数据域小游戏解包后无法正常工作

### ISSUE THREAD

**Issue by xjd1123** [qwerty472123/wxappUnpacker#44]
游戏小程序算是比较特别的一种小程序吧，缓存包都比较大！
[game.zip](https://github.com/qwerty472123/wxappUnpacker/files/1979967/game.zip)

**Comment by qwerty472123** [comment]
见 #10 #41
小游戏不是小程序，小程序有wxml.wxss等。和小游戏都有js和包文件格式都是wxapkg以外没有相同点。
js本身当然不可能自动反混淆
剩下的小游戏解包应该还好吧

**Comment by qwerty472123** [comment]
本来程序不支持自动拆分开放数据域的文件，现已改进
