### ISSUE TITLE
包里面只能还原部分，mch目录的文件值还原了json，其他的都是空

### ISSUE THREAD

**Issue by kakaxi114** [qwerty472123/wxappUnpacker#47]
包里面只能还原部分，mch目录的文件值还原了json，其他的都是空
下载包：链接: https://pan.baidu.com/s/1n19s60tEFnAdqsyy6uJ9vw 密码: hw4j

**Comment by qwerty472123** [comment]
参见 #34 #35 插件、分包会造成部分内容不在同一个wxapkg包内部，所以你需要在缓存中找到一些其他包，这些内容将保留在这些其他包中
目前本程序尚不支持对多个包用`node wuWxapkg.js ...`命令直接全自动处理，这个实在是有点麻烦，以后有空了补上
