### ISSUE TITLE
小程序css解出故障，0.6vv_20180125版本 let thisValue=son.value.children.head&&son.value.children.head.data.name;

### ISSUE THREAD

**Issue by kakaxi114** [qwerty472123/wxappUnpacker#48]
0.6vv_20180125版本
 let thisValue=son.value.children.head&&son.value.children.head.data.name;
                                                                                         ^
TypeError: Cannot read property 'head' of undefined
    at List.node.children.each (D:\moban\xcx17\wuWxss.js:104:41)
辛苦看一下
包下载：链接: https://pan.baidu.com/s/10sg4yun0knN4KvNaxIbRvg 密码: mhy5

**Comment by qwerty472123** [comment]
已更新
