### ISSUE TITLE
解出来之后代码包大小超过2M，这是为什么，怎么优化

### ISSUE THREAD

**Issue by zjjzff1** [qwerty472123/wxappUnpacker#57]
解出来之后代码包大小超过2M，这是为什么，怎么优化

**Comment by qwerty472123** [comment]
代码包就有这么大
可能引入了一些库什么的

2M算什么，android动不动100M的呢...

**Comment by zjjzff1** [comment]
关键小程序不是有2m限制吗，但是源程序确实上传成功的，而解析出来超过2m就没法上传了

**Comment by qwerty472123** [comment]
比如上传前js压缩过了
或者js美化的时候大小用了四个空格而非tab超了
这个不在本程序的考虑范围内
手工改一些把
