### ISSUE TITLE
解wxml和wxss出错。page-frame.html有问题？

### ISSUE THREAD

**Issue by uax** [qwerty472123/wxappUnpacker#58]
程序执行命令(可选):
node wuWxml.js q.wxapkg.unpacked/page-frame.html
程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
/wxappUnpacker/node_modules/vm2/lib/main.js:218
			throw this._internal.Decontextify.value(e);
			^
vm.js:32
return new x;
^^^^^^
```
也试了用其他方式还原的wxapkg包，都是同样错误，可能解析出来的page-frame.html有问题？
原包如下附件：

[q.wxapkg.zip](https://github.com/qwerty472123/wxappUnpacker/files/2043369/q.wxapkg.zip)

**Comment by 305611410** [comment]
应该是你的包的格式问题，要求好像是18.01之后上传的包。我的也是这个问题，不知道怎么版
![image](https://user-images.githubusercontent.com/29944955/40641854-c2dcf9bc-634d-11e8-8855-67821dda2f7b.png)

**Comment by qwerty472123** [comment]
低版本的兼容性请自行解决
本项目恕不做适配工作...
