### ISSUE TITLE
生成小程序自定义组件(Component)时，json 文件缺失

### ISSUE THREAD

**Issue by jun1st** [qwerty472123/wxappUnpacker#65]
如果小程序使用了自定义组件，在反编译时，生成的Component文件中缺失一个<code>json</code>格式的文件， 文件内容就一句话：

```
{
    "components": true
}
```

[微信文档](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/)

组件，都是以 <code>.component.xx</code>的形式结尾的， 

<img width="320" alt="screen shot 2018-06-02 at 22 55 11" src="https://user-images.githubusercontent.com/140474/40877716-08c227c8-66b8-11e8-9398-a8496522124c.png">

截图中的 .component.json 是我手动创建的，

小程序：
[_1318312913_73.zip](https://github.com/qwerty472123/wxappUnpacker/files/2065081/_1318312913_73.zip)

**Comment by qwerty472123** [comment]
components 信息在编译后已经丢失
文件名后缀中 有 component 应该只是该小程序作者个人习惯 微信文档中查不到此要求
目前会基于其他`json`中的`usingComponent`的有无来推断这个文件是否需要加这么一个`json`(这样是最小必要的)
当然如果有兴趣 通过 wxml中的`slot`的有无来判断也是一种思路。
