### ISSUE TITLE
是不是不能解析 wepy 或者 mpvue 的小程序

### ISSUE THREAD

**Issue by billLiao** [qwerty472123/wxappUnpacker#69]
解析了好几个小程序，发现一部分可以解析，一部分不能解析。所以猜想是不是只能解析使用小程序原生写法不使用第三方框架的内容才能解析。

![](http://ww2.sinaimg.cn/large/87c01ec7gy1fs2rhgisprj20bi08874g.jpg)

**Comment by qwerty472123** [comment]
和第三方框架无关
和程序版本 是否使用component和worker和一些高级用法有关（后几个更有可能是解不完全
当然wepy只会还原到被微信编译前、被wepy编译后
