### ISSUE TITLE
只是一个个人意见

### ISSUE THREAD

**Issue by haijun96** [qwerty472123/wxappUnpacker#7]
还是很欣赏作者的分享精神，我之前也写过 一个解析，后来写成了工具，但是我后来发现，淘宝店，盗版微擎群，各种论坛，都有人在用，或者卖。辛苦写的东西，成了人家 赚黑钱的工具，让我很难受。就像我之前听到的一个奸商说的就等着有人共享出解析方法。他就能赚更多钱。，希望作者注意点。反正出事了，他们没事 。你有事。

**Comment by qwerty472123** [comment]
@haijun96 
我的看法是
1. 首先这个“解析”中唯一可能涉及到**逆向**的是 wxapkg 解包，和我没关系，是网上广泛流传的版本。剩下的最多是明文js脚本分析，这样的工具，比如"破解**百度云**"之类的多的去了。
2. 我的锅...想来当初应该选 AGPL v3, 虽然事实上阻止不了他们用就是了。
3. 微信小程序前端能解析出个什么来，仅是好玩而已。而且如果只想改个域名加个广告重新上线也不需要用到我的解析，字符串替换就好了。加上微信限制域名访问的政策，“窃取”应用最大的阻碍是伪造后端吧，出事就跟我没关系了。
4. 有些工具是像你说的那样，我以前云盘火的时候偶然间发现过一个快速增加容量的方法（各种论坛/淘宝什么的就算了，假装成为发现人提交漏洞的都有，到后来我那个帖子上还有人质问我抄袭呢），也是有所体会。
5. 没感到微信小程序**前端**有多么复杂，复杂的我的那破脚本也解析不了。

**Comment by bmy5585** [comment]
我这种小白会觉得作者很伟大。

**Comment by haijun96** [comment]
那些盗版微擎应用就差这种小程序源码，只要改个域名就好，还能够自己二次开发。好在你的还原还差很多东西。

**Comment by qwerty472123** [comment]
@haijun96 我这除了对wxml的还原外都是很快就能做出来的东西
改个域名什么的wxapkg上直接改感觉也很简单啊
二次开发的话 小改动直接盲改就好
大改动因为微信会把所有的js文件压缩，这部分变量名还原基本不可能，还不如重写
我写这些代码目的也就是能让一个微信小程序能在电脑上（wx开发者工具的内置模拟器里）基本能够跑起来，现在甚至没有那个目的了，就单纯好玩，自然不会太过深入研究

**Comment by haijun96** [comment]
@qwerty472123  我也是想研究玩的，后来 变了质。尤其一些奸商玩小号搞套路

**Comment by qwerty472123** [comment]
其实奸商卖一卖什么的也不影响我研究玩的乐趣，**希望**没有相关**"纠纷"**就好。（其实tx应该也不管qq/微信上小打小闹）。
不过现在我同意你小程序源码很重要的观点了。bmy5585给我的”所谓源码“里，居然有`wx:for-item="item" wx:for-index="index"`这样的内容（这两个便签不写，默认值就是item index）。"很可能"这玩意早已被奸商拿去用了。

**Comment by haijun96** [comment]
@qwerty472123   我刚才 看了下那个 ，就是我之前还原的，被一个奸商套路去了，是人人商城的小程序源码，那个wx:for  和尤其css  样式 格式 完全就是我的工具风格，100%出自我手，

**Comment by haijun96** [comment]
@qwerty472123  wx-picker  那个我之前 没注意到 所以 会出现问题。不知道奸商 卖了多少份。

**Comment by qwerty472123** [comment]
emmm 我还能说什么呢....

**Comment by bmy5585** [comment]
空白昵称 哭脸头像 的那个人就是你说的奸商么？我在他哪里买的。

**Comment by haijun96** [comment]
@bmy5585  明周？

**Comment by bmy5585** [comment]
我不知道叫什么，头像是一个卡通哭脸，没有昵称（空白）。这个确实是人人的前端，对方承诺100%可用，稳定运行。我们要做一个门店的小程序，就买了这个，确实可以稳定应用到人人，但是这个代码全部压缩，二开太累了，才学习自己反编。来到这里。

**Comment by haijun96** [comment]
你花了多少？

**Comment by bmy5585** [comment]
看你们讨论，如果你们站在我们这些底层应用人群考虑也许有不同的观点。 qwerty的这个工具给了我这样小白很多学习的机会。哪些靠这个赚钱的人看到这个工具可能不舒服，对于没有这个技术能力的人这是莫大福利。

**Comment by bmy5585** [comment]
@haijun96 我是在承诺不对外传播，不销售的情况下800元买的。

**Comment by IMYalo** [comment]
微擎就是个垃圾而已
