### ISSUE TITLE
小程序插件wxss解析失败 ，v0.6vv_20180522_fbi

### ISSUE THREAD

**Issue by kakaxi114** [qwerty472123/wxappUnpacker#71]
小程序插件wxss解析失败 ，v0.6vv_20180522_fbi

ReferenceError: $gwx1 is not defined
    at vm.js:3:3
    at ContextifyScript.Script.runInContext (vm.js:59:29)

下载包：链接: https://pan.baidu.com/s/1hcRVdnJK7jMrpohKLyaKQw 密码: pz5m

**Comment by qwerty472123** [comment]
失败已经修正
关于`__wxAppCode__`中的内容保存到其他文件夹中
如本应保存在`aa\bb\cc`下的保存在`aa\bb\aa\bb\cc`下的问题将在解决 #35 的自动化问题时解决。
现可手动复制。
