### ISSUE TITLE
小程序插件wxss解析失败 ，v0.6vv_20180522_fbi，ReferenceError: $gwx0 is not defined

### ISSUE THREAD

**Issue by kakaxi114** [qwerty472123/wxappUnpacker#72]
小程序插件wxss解析失败 ，v0.6vv_20180522_fbi，ReferenceError: $gwx0 is not defined

包下载：链接: https://pan.baidu.com/s/1GLc1iERUfeua8TfTepZzSw 密码: ne8d

**Comment by qwerty472123** [comment]
请不要重复提交同一类型的bug
