### ISSUE TITLE
未找到 app.json 中的定义的 pages "pages/active_page/group_scan/group_scan" 对应的 WXML 文件

### ISSUE THREAD

**Issue by aa335418265** [qwerty472123/wxappUnpacker#75]
wxakpg版本：v0.6vv_20180522_fbi

程序执行命令(可选):
```
node /Users/itx/wxappUnpacker/wuWxapkg.js ./"${rename}"
```
输出结果
```
未找到 app.json 中的定义的 pages "pages/active_page/group_scan/group_scan" 对应的 WXML 文件
```

尝试了很多个小程序，在page下代码都只有.json文件，没有wxml文件和js文件,从而报错！

**Comment by qwerty472123** [comment]
page下代码都只有.json是因为分包 你要找全所有包 然后参考 #35 手动解包
目前暂不支持自动解包分包的程序

**Comment by aa335418265** [comment]
我在微信沙盒目录，只找到一个wxapkg文件，没有发现有分包

**Comment by qwerty472123** [comment]
...然而你不给样本的话我只能猜啊，我只能猜已有Issue中的可能...

**Comment by aa335418265** [comment]
链接:https://pan.baidu.com/s/1Hm1eO3_3th_MFuZWq0s5fw  密码:59pj

每日优鲜
