### ISSUE TITLE
Error: Save file error: Error: ENOENT: no such file or directory, open 

### ISSUE THREAD

**Issue by aa335418265** [qwerty472123/wxappUnpacker#80]
程序执行命令(可选):

 node ~/wxappUnpacker/wuWxapkg.js ./f6de052da5316347d90f07ff05982386_1.wxapkg 

```
/Users/itx/wxappUnpacker/wuLib.js:72
		if(err)throw Error("Save file error: "+err);
		       ^

Error: Save file error: Error: ENOENT: no such file or directory, open '/Users/utils/components/user_no_rule/user_no_rule.json'
    at ioLimit.runWithCb.err (/Users/itx/wxappUnpacker/wuLib.js:72:16)
    at agent (/Users/itx/wxappUnpacker/wuLib.js:54:14)
    at fs.js:1280:7
    at FSReqWrap.oncomplete (fs.js:135:15)
```

**Comment by wonderffee** [comment]
我上午也发现这个问题了，应该是组件解析出问题了吧，component是没有index.json的，而且上面的路径/Users/utils也存在问题，根路径似乎弄错了
用老版的测试反而没有问题

**Comment by wonderffee** [comment]
我记起来之前一个线上项目反编译后运行出错，解决办法是类似这个issue: https://github.com/qwerty472123/wxappUnpacker/issues/65 中的对组件添加index.json，并在其中输入:
```
{
    "components": true
}
```
才得以运行正常的。所以component还是应该需要index.json的

**Comment by wonderffee** [comment]
解决起来也比较简单，问题在于组件的路径有两种形式，一种是以../开头的，这种处理是正常的，有问题的是以/开头的，它是相对于项目文件夹根路径的，toDir函数会把这种路径处理成类似于../../../../../这种相对路径，与项目根路径进行整合时就会出问题
已经提交新的pull request

**Comment by qwerty472123** [comment]
这样啊 是我修 #65 的时候缺乏考证了 抱歉
感谢 @wonderffee 的分析

**Comment by aa335418265** [comment]
3Q两位老哥

**Comment by Liyoh** [comment]
我也是这个错误，但是现在不能用了
