### ISSUE TITLE
只生成.json文件，缺失wxml和js文件，没有发现有分包

### ISSUE THREAD

**Issue by aa335418265** [qwerty472123/wxappUnpacker#82]
链接:https://pan.baidu.com/s/1hbR2xUpzCU9NXGiHQGRMUw  密码:bfqw

```
未找到 app.json 中的定义的 pages "pages/active_page/group_scan/group_scan" 对应的 WXML 文件
```

从根目录开始递归遍历，值有一个wxapkg包，没有发现作者说的“分包”的情况！
```
umiumi:~ root# find / -name "*.wxapkg"
/private/var/mobile/Containers/Data/Application/33D401A8-A135-4D45-89F7-21C4148DC68B/Library/WechatPrivate/013d83ca7c1c1c67a4f8e9c3c9225339/WeApp/LocalCache/release/wxebf773691904eee9/100/Module/f6de052da5316347d90f07ff05982386.wxapkg
```

**Comment by qwerty472123** [comment]
请勿重复发帖。
这个wxapkg中根本不存在你要的那些文件的信息，打死也还原不出来，这样发帖没有意义
你找不到这个分包的原因是多样的 比如
微信或小程序可能存在配置使得它用后即删
微信可能采用了使用分包中内容才会加载分包的策略（不然分包意义何在？），但同样的策略不适用于pc端调试，因为它需要完整的编译所有文件然后运行（或许你可以尝试移除分包内的代码于外部代码的关联来运行）。
