### ISSUE TITLE
怎么找到当前用户 用户名呀

### ISSUE THREAD

**Issue by sailei1** [qwerty472123/wxappUnpacker#83]
我没发现 /data/data/com.tencent.mm/MicroMsg/{user}/appbrand/pkg
这样的目录

**Comment by qwerty472123** [comment]
说的很清楚啊：
其中`{User}`为当前用户的用户名，是类似于`2bc**************b65`这样的字符串。
你在`/data/data/com.tencent.mm/MicroMsg/`下四处找找不就找到了...
系统与微信版本差异也会又问题
但这不是本项目讨论的话题，相关话题在跳一跳最火的时候已被充分讨论，如有需要请利用搜索引擎搜索当时的各种文章
