### ISSUE TITLE
请问模块形式加载的无法解wxss文件吗？

### ISSUE THREAD

**Issue by zhujitop** [qwerty472123/wxappUnpacker#85]
最近看某个小程序，分包了好几个，有几个是以插件模块形式加载的。
里面的.wxapkg解出来之后有：
app-service.js， page-frame.js两个文件，没有page-frame.html或app-wxss.js。

然后用node wuJs.js app-service.js可以解出来js文件
用node wuWxml.js page-frame.js可以解出来xml文件

pages文件夹里面都有html文件，html看代码是wxss，但是用这个工具不能把html转换成wxss文件。

主程序没问题，可以全部解出来。
是目前这个脚本还不支持插件形式的吗？

[插件.zip](https://github.com/qwerty472123/wxappUnpacker/files/2103779/default.zip)

**Comment by qwerty472123** [comment]
可以这样`node wuWxss.js _-1743477122_27\pages\groups`

**Comment by BartSu** [comment]
![image](https://user-images.githubusercontent.com/23166423/41509971-16ad1478-728f-11e8-9c7b-3a4b5ce5c328.png)
wuWxml 和 wuWxss两种形式都不行，？is not defined 是怎么回事，这个小程序我之前上传过了，是因为分包的缘故吗？
