### ISSUE TITLE
解包提示：SyntaxError: Unexpected token } v0.6vv_20180125_fbi

### ISSUE THREAD

**Issue by kakaxi114** [qwerty472123/wxappUnpacker#88]
提示node_modules\vm2\lib\main.js:218
                        throw this._internal.Decontextify.value(e);
                        ^
SyntaxError: Unexpected token }

版本是v0.6vv_20180125_fbi

包下载地址：链接: https://pan.baidu.com/s/1ys43Hd6dvfHJPOpzzHQxiw 密码: 43s2

**Comment by qwerty472123** [comment]
小程序内含插件暂不支持解包 见 #73 
七月再更新
