### ISSUE TITLE
<block wx:if="{{member.needbind==1}}"> 类似 block 都过滤掉了是么？

### ISSUE THREAD

**Issue by bmy5585** [qwerty472123/wxappUnpacker#9]
我反编译的是一个 cms 类的小程序前端 手里有源码 和下载下来的反编译比较了以下发现

<block wx:if="{{member.needbind==1}}">

这样的都过滤掉了，反编译后和原来的差别还是很大的。

**Comment by marty0929** [comment]
```
<block wx:if="{{real_value}}">
        <view catchtap="{{data.eventHandler}}" class="element picture" data-event-params="{{data.eventParams}}" data-imgArr="{{real_value}}" style="{{data.style}}" wx:for="{{real_value}}" wx:if="{{pictureWxsModule.isArray(real_value)}}">
            <image mode="scaleToFill" src="{{real_value.index}}"></image>
        </view>
        
    </block>
```

这个是我编译之后的样子，都完全正常

**Comment by bmy5585** [comment]
源码不方便公开发布，可以给我留一个邮箱发给你。（高价买来的，承诺了不公开发布或出售）

<view class="picker-modal city-picker {{showPicker?'in':'out'}} {{iphonexnavbar}}">
  <view class="picker-control">
    <view bindtap="onCancel" class="cancel">取消</view>
    <view bindtap="onConfirm" class="confirm">确定</view>
  </view>
  <block wx:if="{{!noArea}}">
    <picker-view bindchange="bindChange" class="picker" indicatorStyle="height: 40px;" value="{{pval}}">
      <picker-view-column>
        <block wx:for="{{areas}}" wx:for-item="item" wx:for-index="index">
          <view class="item">{{item.name}}</view>
        </block>
      </picker-view-column>
      <picker-view-column>
        <block wx:for="{{areas[pval[0]].city}}" wx:for-item="item" wx:for-index="index">
          <view class="item">{{item.name}}</view>
        </block>
      </picker-view-column>
      <picker-view-column>
        <block wx:for="{{areas[pval[0]].city[pval[1]].area}}" wx:for-item="item" wx:for-index="index">
          <view class="item">{{item.name}}</view>
        </block>
      </picker-view-column>
    </picker-view>
  </block>
  <block wx:if="{{noArea}}">
    <picker-view bindchange="bindChange" class="picker" indicatorStyle="height: 40px;" value="{{pval}}">
      <picker-view-column>
        <block wx:for="{{areas}}" wx:for-item="item" wx:for-index="index">
          <view class="item">{{item.name}}</view>
        </block>
      </picker-view-column>
      <picker-view-column>
        <block wx:for="{{areas[pval[0]].city}}" wx:for-item="item" wx:for-index="index">
          <view class="item">{{item.name}}</view>
        </block>
      </picker-view-column>
    </picker-view>
  </block>
</view>

这个是一个片段。

**Comment by qwerty472123** [comment]
@bmy5585 理解不公布的做法，刚才那个片段我看了，应该足够了，对wx:for处理的确有问题，我修复试试看。
如果想直接发源码在代码前后都加上有```的一行就ok了（因为md支持部分html）

**Comment by qwerty472123** [comment]
@bmy5585 
emmm...其实还好
你可以仔细看看，例如
```
        <block wx:for="{{areas[pval[0]].city}}" wx:for-item="item" wx:for-index="index">
          <view class="item">{{item.name}}</view>
        </block>
```
会被改成
```
<view class="item" wx:for="{{areas[pval[0]].city}}">{{item.name}}</view>
```
你可以注意到不写`wx:for-item`的话，默认值就是item，`wx:for-index`的默认值就是index，省不省无所谓的。
同时，写在`block`内的只有`view`，这个`block`是**不必要**的,直接把`wx:for`写在`view`上没有任何问题。

这两处不同的写法在微信编译后都是一样的（即具体怎么写的信息丢失了），无法还原作者真正的写法。
为了更加贴合**“真实”**的情况，我认为一个**”正常“**的程序员更倾向于写缩写，即更简短的格式，所以统一会自动改成缩写的格式。

老实说我现在认识到说的问题了，你这个代码一点缩写（而且缩写通常是在微信小程序教程更前面的地方出现）都不用，而不缩写的形式其实更方便程序还原（你可以看看我的代码，我是先处理出没缩写的格式后简化代码的），所以我**怀疑**你的这部分的代码很可能由**程序生成**，且这个生成与从已”编译“的wxml中**”还原“**的过程很相似。

**Comment by qwerty472123** [comment]
@bmy5585
看了一下你提供的wxss代码 这点上应该基本上可以说**超越合理**了吧。
微信小程序编译过程中会把`picker-view-column`这样的tag-name修改成`wx-picker-view-column`，这是任何一个正向开发都不会干的。（同时wxss完全符合微信压缩后的格式）

**Comment by bmy5585** [comment]
你的意思是，我买的这个代码也是反编译来的是么？
