### ISSUE TITLE
还有在更新吗

### ISSUE THREAD

**Issue by Wfuren** [qwerty472123/wxappUnpacker#90]
![default](https://user-images.githubusercontent.com/29916783/41635084-66d34396-7479-11e8-955b-8a999c0d5720.png)
不知道还在更新吗，反编译出现的问题呢。。大牛可以解决一下吗

**Comment by qwerty472123** [comment]
7月一定更新，到时候把 提供对小程序插件的支持 提供小程序多线程(Worker)的支持 提供对带分包的小程序包插件部分的支持 这三个issue解决掉
现在是每时间
另外你这个似乎是小程序版本太老的原因，不在更新范围内...

**Comment by Wfuren** [comment]
....这就尴尬了，你指的是微信工具编译的时候基带版本吗？？？能帮忙解决下吗

**Comment by qwerty472123** [comment]
不解决旧版本的原因前面issue里提过 如有需要自己适配

**Comment by Wfuren** [comment]
应该不存在版本的问题啊我记得版本是1.7或者1.8的，不会很低的啊。这小程序是我今年还是17年10月份做的
这是解码后文件的名字
![default](https://user-images.githubusercontent.com/29916783/41704299-749ad68e-7568-11e8-896b-3189645439bf.png)
以下是内容
![default](https://user-images.githubusercontent.com/29916783/41704328-82f9258c-7568-11e8-8955-bdc0a4ace4ec.png)

**Comment by qwerty472123** [comment]
可以看看readme吗？
我支持（包括计划将支持）的版本是所有`wcc.exe`版本大于`v0.6vv_20180111_fbi`的
