### ISSUE TITLE
小程序开发者工具编译后，提示找不到未找到WXML 文件

### ISSUE THREAD

**Issue by XiaoLiz** [qwerty472123/wxappUnpacker#93]
小程序 编译成功， 添加到小程序开发者工具提示错误：

文件目录：

![image](https://user-images.githubusercontent.com/15154383/42140275-f8d14cca-7dcf-11e8-83c5-0db1f2e71ac4.png)

控制台提示：

![image](https://user-images.githubusercontent.com/15154383/42140320-8d754fc0-7dd0-11e8-84ed-14a238b306d6.png)

**Comment by igo9go** [comment]
有解决吗，也遇到同样问题

**Comment by qwerty472123** [comment]
应该是存在分包
分包在别的包中
目前只能手动处理这个情况
过几天会支持半自动处理
