### ISSUE TITLE
安装项目的模块依赖 js-beautify 报错

### ISSUE THREAD

**Issue by muzishuiji** [qwerty472123/wxappUnpacker#95]
把你的项目克隆下来之后安装项目所需要的依赖,当安装到   **js-beautify** 这个模块的时候报错,

报错信息如下:
`npm ERR! Unexpected end of JSON input while parsing near '...tatic":"~0.7.1","must'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hzljie\AppData\Roaming\npm-cache\_logs\2018-07-04T02_34_14_441Z-debug.log`

想请教你这个报错是为什么.怎么解决啊?

**Comment by qwerty472123** [comment]
这似乎不是本项目的问题，请上网查询解决方案或隔几天重试
