### ISSUE TITLE
反编时出现了个Error：This Package is unrecognizable, please decrypted every type of file by hand.

### ISSUE THREAD

**Issue by MyGyo** [qwerty472123/wxappUnpacker#98]
请问是什么问题？What's the problem?

**Comment by igo9go** [comment]
解压的文件类型就不一样
![image](https://user-images.githubusercontent.com/11486721/42444405-93a9489c-83a2-11e8-95c9-412776127da4.png)

**Comment by qwerty472123** [comment]
非小程序小游戏包
