### ISSUE TITLE
解包显示 throw this._internal.Decontextify.value(e);   /*v0.6vv_20180522_fbi*

### ISSUE THREAD

**Issue by kakaxi114** [qwerty472123/wxappUnpacker#99]
/*v0.6vv_20180522_fbi*
node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
SyntaxError: Unexpected token }
    at VMScript.compile 

下载地址：链接: https://pan.baidu.com/s/1YaW7MdWc7D_ZC07kjGNJnw 密码: cvxw

**Comment by qwerty472123** [comment]
这个是包内有插件的原因
与 #73 相同
请等待该issue修复
